### ISSUE TITLE
Screenshots at GitHub README preview have dead links

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#101]
I just get broken pics in the "front page".

**Comment by jeaye** [comment]
On Mon, Dec 14, 2015 at 09:05:36PM -0800, Francisco Lopes wrote:
>    I just get broken pics in the "front page"

Thank you! I've been doing some server work and these were inadvertently
broken. Fixing now...

**Comment by oblitum** [comment]
Just one has been restored for me.

**Comment by oblitum** [comment]
one of four.
