### ISSUE TITLE
Macvim from macports or Arch linux leads to ncurses issues

### ISSUE THREAD

**Issue by Berteun** [jeaye/color_coded#104]
Let's take this simple file:

```
#include <iostream>

int main() {
	std::cout << "Hello World!\n";
}
```

When using color_coded in a terminal, and when scrolling around eventually something like this happens (results vary, but it is all messed up, typical to having a wrong $TERM setting or something).

<img width="766" alt="screen shot 2015-12-30 at 21 47 45" src="https://cloud.githubusercontent.com/assets/4739718/12057233/11cfbe76-af3f-11e5-9e48-1f9b554f14c3.png">

I have this problem with both iTerm and Terminal.app. It only occurs when color_coded is actually active (like a .c file), just loading it doesn't affect it. When using the GUI version of MacVim, it works correct.

As I said, I am using MacVim from Macports:

```
mvim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 29 2015 16:47:41)
MacOS X (unix) version
Included patches: 1-972
Compiled by MacPorts
```

I tried setting the `term` setting explicitly, and tried setting `t_Co` to 256, but to no avail. I'm a bit stumped how to further explore any possible solutions.

**Comment by jeaye** [comment]
That's crazy. Would you mind sharing your `$TERM`? As you mentioned, I think that may be part of the issue here.

**Comment by Berteun** [comment]
My TERM is xterm-256color (both ITerm and MacVim) I forgot to mention, but I tested with various different settings, like vt100, xterm and xterm-16color as well as running inside of screen (with TERM=screen or screen-256color) and tmux. All lead to the same result.

**Comment by jeaye** [comment]
Ok, will you please try disabling *all config* except for color_coded? I mean *everything* that you don't absolutely need in order to run color_coded. This should be something like:

```viml
set nocompatible
set rtp += /path/to/color_coded
syntax on
filetype plugin indent on
```

With that minimized setup, let me know if you still see the issue.

**Comment by Berteun** [comment]
Same issue. If I do 'syntax off' (leave out the filetype line completely) then obviously everything is fine. When I then do `:syntax on` followed by `:e` to reload the CC file, the corruption starts.

**Comment by Berteun** [comment]
I tried updating MacVim to snapshot 88; same effect. Switched to the 'standard' vim in the macports bundle (of course compiled with +lua), and it also displays the same behaviour with the minimal config file.

**Comment by jeaye** [comment]
Alright. There has to be something wonky, in your environment, which is causing this, color_coded simply doesn't have the functionality to even cause something like that; it only enables/disables highlighting of certain words. It doesn't move any text around.

Unfortunately, what might be wrong with the environment isn't coming to me right now; it's highly unlikely that this is due to incorrect functionality in color_coded, however, due to how many platforms currently use it without issue. I'm going to leave this open, though, and hopefully we can brainstorm what might be causing this.

**Comment by Berteun** [comment]
I dug a bit further, which led me to suspect it was some weird ncurses interaction, and presto, this is a similar issue for Clang Complete: [https://github.com/Rip-Rip/clang_complete/issues/453] which has led to this issue in the LLVM bug tracker [https://llvm.org/bugs/show_bug.cgi?id=25007] -- long story short, it is a bug in the clang library that reinitialises the terminal. A work-around is to create a `.color_coded` file with `-fcolor-diagnostics` in there.

So it is not a color_coded issue, but on the other hand is not unlikely that more people run into it.

**Comment by jeaye** [comment]
@Berteun Woah, good find. Is `-fcolor-diagnostics` something you think should be in by default, so nobody has this issue?

**Comment by Berteun** [comment]
Yes as far as I can see there's no negative impact so it seems sense as a workaround.

**Comment by Arondight** [comment]
@Berteun How about a cpp file? I add `-fcolor-diagnostics` to `~/.color_coded` and everything goes well on c file, but cpp file still has problem.

**Comment by bstaletic** [comment]
Encoutered this issue with both clang_complete and youcompleteme when using libclang. 
Note: I do not use color_coded, but I have some more information regarding the bug not mentioned here yet.

As Berteun said:
 >long story short, it is a bug in the clang library that reinitialises the terminal.

One can work around this bug in a few ways:
* Ask libclang politely not to do this using the `-fcolor-diagnostics` though Arondight says it doesn't work in cpp
* Redirect vim's stderr to anything. Strangely this won't write anything to the file, so it doesn't provide any new info about the bug and makes it harder to read the actual errors from vim.
* Compiling llvm without ncurses support, this is the best choise but requires manually building a HUGE package.

**Comment by f-koehler** [comment]
Adding `-fcolor-diagnostics` works in C++ for me as well. But I compiled against the clang/LLVM (3.8.1) of my distribution (ArchLinux) using
```bash
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DDOWNLOAD_CLANG=OFF \
    -DLLVM_CONFIG=/usr/bin/llvm-config ..
```
