### ISSUE TITLE
Vim segmentation fault

### ISSUE THREAD

**Issue by cnchyan** [jeaye/color_coded#107]
Vim crashes frequently when editing c-family files.
This is the stack trace:
#0  0x00005555555dd0c5 in set_ref_in_item ()
#1  0x00005555555dd326 in set_ref_in_list ()
#2  0x0000555555753c11 in ?? ()
#3  0x00007ffff4a9092d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#4  0x00007ffff4a90c62 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#5  0x00007ffff4a8cd0b in lua_callk ()  from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#6  0x000055555575534a in set_ref_in_lua ()
#7  0x00005555555e6c3f in garbage_collect ()
#8  0x00005555556af3e7 in mch_inchar ()
#9  0x000055555572bef0 in ui_inchar ()
#10 0x000055555563dba3 in inchar ()
#11 0x000055555563fb65 in ?? ()
#12 0x00005555556403d6 in vgetc ()
#13 0x0000555555640839 in safe_vgetc ()
#14 0x000055555568e6e5 in normal_cmd ()
#15 0x00005555557712c5 in main_loop ()
#16 0x00005555555b3ae6 in main ()

**Comment by jeaye** [comment]
@cnchyan See #68.

**Comment by cnchyan** [comment]
so fast , much thanks!
