### ISSUE TITLE
Vim: Caught deadly signal SEGV when editing .c file with color_coded enabled

### ISSUE THREAD

**Issue by antonvesnin** [jeaye/color_coded#110]
vim crashes on SIGSEGV while editing file.

It happend with default vim on ubuntu 15.10, it crashes just affter opening a file or after some small editing. I tryed to build vim from source, and it was still crashig with the same message. As i saw in backtrace it has something to do with luajit (i'm not shure), and recompiling vim with lua, but without luajit looks helpful (didn't crash yet, but i'm still testing). Is it possible to fix problems with luajit, or it's vims issue and should be reported there? Thanks.

**Comment by jeaye** [comment]
If you're using luajit, you won't be able to use color_coded -- the readme has more info on that. If your crash is lua-related, but not luajit-related, then, since you're on Ubuntu, I'll direct you to https://github.com/jeaye/color_coded/issues/68.

**Comment by jeaye** [comment]
The only way I can be certain is if you provide your crash info and back trace.

**Comment by antonvesnin** [comment]
You right the trace was the same like in #68, but it had nothing to do with tmux, it just happend, i think the bug is somehow still there, but is it in vim or color_coded i don't know. Got you about luajit, thanks.

**Comment by jeaye** [comment]
@antonvesnin You need to read the last comments of #68.

**Comment by jeaye** [comment]
I've also updated #68 to be more clear, upon first glance.
