### ISSUE TITLE
Update notes for building (15.10)

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#111]
Making this into an issue for the moment since I don't want to suggest something that breaks older ubuntu's.

`sudo apt-get install libclang-3.7 liblua5.1-dev lua5.1 cmake`

It will not find or use lua 5.3 if its installed.

`cmake .. -DCUSTOM_CLANG=1 -DLLVM_ROOT_PATH=/usr -DLLVM_INCLUDE_PATH=/usr/lib/llvm-3.7/include -DCLANG_LIBS=/usr/lib/llvm-3.7/lib`

Note:  ``/usr/lib/clang/3.7`` and ``/usr/lib/clang/3.7.0`` and their subdirectories had no relation to the ``CLANG_LIBS`` FindClang.cmake module was looking for.

**Comment by jeaye** [comment]
I think I've found the issue: https://github.com/jeaye/color_coded/blob/master/cmake/FindLua.cmake#L69

**Comment by jeaye** [comment]
@tony Will you add 3 to that list, before 2, and let me know if it ends up finding lua 5.3 for you? If so, this should be a simple fix.

**Comment by tony** [comment]
Yep, I'll do all, QA on 15.10 and update the docs.
