### ISSUE TITLE
How to handle files not supposed to be included directly ?

### ISSUE THREAD

**Issue by wichtounet** [jeaye/color_coded#116]
Hi, 

I was wondering if you had any trick to handle files that are not supposed to be included directly. I'm working on an header-only library with only two headers that are supposed to be included and that includes the necessary header themselves. 

When I work on an header not supposed to be included, it is missing a lots of dependencies (shown in CCerror), which is logical. 

Is there any option to handle this corner case ?

Thanks

**Comment by jeaye** [comment]
If you just want highlighting in those files, as though they've been included properly, you might try adding `-include <proper include>` to your `.color_coded`. This will prefix every compilation unit with the specified file, as though it had been included. Perhaps that matches what you need?

**Comment by wichtounet** [comment]
Good idea, I didn't though of that. 

It took  me a long time to figure out that I had to put in two lines in the `.color_coded` file. 

```
-include
etl/etl.hpp
```

If I put it on one line, it try to include a file starting with a space, not finding it. If I surround the lines by quotes (" or ' or `), it makes libclang crash. 

But now, I have another error: 

> /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found

I guess it comes from the clang compiled with color_coded ?

**Comment by jeaye** [comment]
On Tue, Mar 22, 2016 at 03:53:27AM -0700, Baptiste Wicht wrote:
> Good idea, I didn't though of that. 
> 
> It took  me a long time to figure out that I had to put in two lines in the `.color_coded` file. 
> 
> ```
> -include
> etl/etl.hpp
> ```
> 
> If I put it on one line, it try to include a file starting with a space, not finding it. If I surround the lines by quotes (" or ' or `), it makes libclang crash. 

The README covers that, so I didn't mention it in my suggestion. :P

> But now, I have another error: 
> 
> > /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found
> 
> I guess it comes from the clang compiled with color_coded ?

Keep the extracted clang around, in case you deleted it. If you didn't
delete it, let me know: it may be another issue.

**Comment by wichtounet** [comment]
> The README covers that, so I didn't mention it in my suggestion. :P

My bad then ;)

> Keep the extracted clang around, in case you deleted it. If you didn't delete it, let me know: it may be another issue.

This fixed the issue, but it is not over. 

Now, I have redefinitions issues. Apparently pragma once and -include don't play well. I tried include guard and it is worse since now there are no highlighting whatsoever. I guess that since it is already included, the code is not parsed because it is removed by the preprocessor. 

Seems I'm kind of stuck here :(

**Comment by jeaye** [comment]
On Wed, Mar 23, 2016 at 12:23:27AM -0700, Baptiste Wicht wrote:
> > The README covers that, so I didn't mention it in my suggestion. :P
> 
> My bad then ;)
> 
> > Keep the extracted clang around, in case you deleted it. If you didn't delete it, let me know: it may be another issue.
> 
> This fixed the issue, but it is not over. 
> 
> Now, I have redefinitions issues. Apparently pragma once and -include don't play well. I tried include guard and it is worse since now there are no highlighting whatsoever. I guess that since it is already included, the code is not parsed because it is removed by the preprocessor. 
> 
> Seems I'm kind of stuck here :(

You shouldn't be defining anything in the header which will result in
redefinition. Classes/structs should be fine, function and variables
must be declarations only. That's just general good practice.

Are you able to share the header which is causing the issue?

**Comment by wichtounet** [comment]
> You shouldn't be defining anything in the header which will result in redefinition. Classes/structs should be fine, function and variables must be declarations only. That's just general good practice. 

This has nothing to do with my code... You have this error if headers are included multiple times for templates. Why would we have include guards otherwise ?

If you have global.hpp which would be the entry point of the library: 

```cpp
#pragma once
#include "second.hpp"
```

and then second.hpp:

```cpp
#pragma once

template<typename T>
struct asdf {};
```

If you compile second.hpp with: `g++ -include global.hpp second.hpp` which is what color_coded with clang, you get this error: 

> second.hpp:4:8: error: redefinition of ‘struct asdf<T>’
>  struct asdf {};
>         ^
> In file included from ./global.hpp:3:0,
>                  from <command-line>:0:
> ./second.hpp:4:8: error: previous definition of ‘struct asdf<T>’
>  struct asdf {};
>         ^

If we use include guards: 

#ifndef GUARD
#define GUARD
template<typename T>
struct asdf {};
#endif

Compilation works fine but color_coded does not do any highlighting inside the include guard. Which is logical since at the point of the highlighting it has already been included a first time by -include option.

**Comment by jeaye** [comment]
> If we use include guards: 
> 
> #ifndef GUARD
> #define GUARD
> template<typename T>
> struct asdf {};
> #endif
> 
> Compilation works fine but color_coded does not do any highlighting inside the include guard. Which is logical since at the point of the highlighting it has already been included a first time by -include option. 

I see. Unfortunately, then, I don't think this use case is supported;
both color_coded and YCM (and anything else in vim using libclang) will
work best with standalone headers.

**Comment by wichtounet** [comment]
That's what I feared :s 

Thank you for your support ;)
