### ISSUE TITLE
Strange behavior after 3.8

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#120]
When opening a c++ file in vim, it gets stuck, anything I type turn into numbers at the bottom of the screen:

![screenshot from 2016-04-16 13-56-47](https://cloud.githubusercontent.com/assets/1269815/14582439/45c18174-03db-11e6-92d9-deaca0b3ffd3.png)

I'm still able to exit vim even without visual feedback by typing `:q<ENTER>`. After this, strangely, I can't see my cursor at the console window anymore, I have to open another one and discard the previous.

ArchLinux
Vim 7.4.1721

**Comment by jeaye** [comment]
I've seen weird issues with 3.8.0 on Arch Linux, and only on Arch, as well. My guess is that there are some ncurses-related issues with 3.8.0; I wager no amount of C++ changes in color_coded will fix this, since it's a dependency issue.

With that said, it certainly warrants investigation as to what 3.8.0 is now doing with ncurses that it wasn't doing before. The first thing I'd check is that vim and color_coded are linked to the same ncurses. I have an Arch box, but I've just moved into a new place and I'm setting things up still. Once I have a desk and whatnot, after this weekend, I can take out my Arch machine and dig deeper.

**Comment by oblitum** [comment]
hmm, same version. My problem can be related with #119, vim ins linked against a newer liblua.

**Comment by jeaye** [comment]
Ah, interesting.

**Comment by oblitum** [comment]
```
~/.v/p/color_coded ❯❯❯ readelf -d color_coded.so                                                                                                      master ◼

Dynamic section at offset 0x47328 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libclang.so.3.8]
 0x0000000000000001 (NEEDED)             Shared library: [liblua5.2.so.5.2]
 0x0000000000000001 (NEEDED)             Shared library: [libncursesw.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [color_coded.so]
 0x000000000000000f (RPATH)              Library rpath: [/home/francisco/.vim/plugged/color_coded/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/lib]
 0x000000000000000c (INIT)               0x16740
 0x000000000000000d (FINI)               0x3d738
 0x0000000000000019 (INIT_ARRAY)         0x246c70
 0x000000000000001b (INIT_ARRAYSZ)       40 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x246c98
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1b8
 0x0000000000000005 (STRTAB)             0x5010
 0x0000000000000006 (SYMTAB)             0xf90
 0x000000000000000a (STRSZ)              50380 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x247a40
 0x0000000000000002 (PLTRELSZ)           8328 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x146b8
 0x0000000000000007 (RELA)               0x11b50
 0x0000000000000008 (RELASZ)             11112 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x11a40
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x114dc
 0x000000006ffffff9 (RELACOUNT)          163
 0x0000000000000000 (NULL)               0x0
~/.v/p/color_coded ❯❯❯ readelf -d `which vim`                                                                                                         master ◼

Dynamic section at offset 0x28ccd8 contains 45 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libgtk-x11-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk-x11-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk_pixbuf-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgio-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpango-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libSM.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libICE.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXt.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libncursesw.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libacl.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgpm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [liblua.so.5.3]
 0x0000000000000001 (NEEDED)             Shared library: [libperl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libruby.so.2.3]
 0x000000000000000f (RPATH)              Library rpath: [/usr/lib/perl5/core_perl/CORE]
 0x000000000000000c (INIT)               0x432b00
 0x000000000000000d (FINI)               0x605ac4
 0x0000000000000019 (INIT_ARRAY)         0x88ccc0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x88ccc8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400298
 0x0000000000000005 (STRTAB)             0x41d6d0
 0x0000000000000006 (SYMTAB)             0x405610
 0x000000000000000a (STRSZ)              58373 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x88d000
 0x0000000000000002 (PLTRELSZ)           19536 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x42deb0
 0x0000000000000007 (RELA)               0x42dbf8
 0x0000000000000008 (RELASZ)             696 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x42dae8
 0x000000006fffffff (VERNEEDNUM)         5
 0x000000006ffffff0 (VERSYM)             0x42bad6
 0x0000000000000000 (NULL)               0x0
~/.v/p/color_coded ❮❮❮                                                                                                                                master ◼
```

**Comment by oblitum** [comment]
It's the "same" problem, just reversed. If this is culprit of both issues, I guess color_coded should stick with vim's version always.

**Comment by oblitum** [comment]
I'm trying to set CMakeList.txt to pick the default 5.3.2 version of lua from the system but it's refusing, it's just acting stupidly. Should be a bug.

**Comment by oblitum** [comment]
I'm putting `find_package(Lua 5.3.2 EXACT QUIET)` but it just gets 

```
-- Looking for Lua
-- Found Lua
--   Lua include /usr/include
--   Lua lib /usr/lib64/liblua5.2.so;/usr/lib64/libm.so
```

no matter what.

**Comment by jeaye** [comment]
I think it'll do 5.3 or 5.2, but not likely as exact as 5.3.2.

**Comment by oblitum** [comment]
I've tried it first, didn't work...

**Comment by oblitum** [comment]
I have a suspicion detection is being done in a sloppy manner given the pattern I see for multiple lua installations.

I have 5.3, 5.2, and 5.1

includes:

5.3 -> /usr/include
5.2 -> /usr/include/5.2
5.1 -> /usr/include/5.1

libs -> /usr/lib

**Comment by oblitum** [comment]
Ah, I didn't realised that FindLua.cmake had been copied... so it can be fixed from it.

**Comment by oblitum** [comment]
OK. I've applied a sed recursively to patch build files, now color_coded is linked against Lua 5.3, but I still have the same behaviour though :-/

**Comment by jeaye** [comment]
Hm, so it seems this is actually a separate issue?

**Comment by oblitum** [comment]
Yes, after this I conclude it is.

**Comment by oblitum** [comment]
FYI. I've just upgraded ArchLinux and got into issues with YCM related with libclang linking to libtinfo 5 (https://github.com/Valloric/YouCompleteMe/issues/778#issuecomment-211452969). I was getting the issue described here before this upgrade, but still just to make you aware of any problem that may arise related to incompatibilities between libtinfo, ncurses, etc...

**Comment by oblitum** [comment]
The issue still behaves the same after this upgrade.

**Comment by ZWindL** [comment]
Try to add `-fcolor-diagnostics` in your .color_coded file.
I have the same problem with you. And my vim also say `/usr/include/wchar.h:39:11: fatal error:  stdarg.h' file not found` when I type `:CCerror`.

**Comment by jeaye** [comment]
@ZWindL To resolve that `stdarg.h` issue, if you're on OS X, please install Xcode's command line tools. The README covers how to do this.

**Comment by ZWindL** [comment]
@jeaye I'm an Arch user, that distribution has lots problems with clang libs.

**Comment by oblitum** [comment]
I'm also an Arch user (almost exclusively lately), but my experience is contrary, besides color_coded I didn't hit any wall with any other project.

**Comment by jeaye** [comment]
I believe this is actually a duplicate of #104, except now showing up on Arch.

**Comment by oblitum** [comment]
Let's try this `fcolor-diagnostics` thing!

**Comment by oblitum** [comment]
Fixed!

**Comment by oblitum** [comment]
I'll close as duplicate, since that other one should suffice to be left open to add this as default.

**Comment by oblitum** [comment]
Also, thanks @ZWindL, you suggested this 3 days ago ;-). At least the issues are linked now.

**Comment by oblitum** [comment]
I've just updated the plugin and rebuilt, I'm now also getting the error message @ZWindL referred to, and highlighting isn't  as good as before this new build...

**Comment by oblitum** [comment]
Did something change about include headers lookup? Because in this meantime, clang version didn't change, it used the cached 3.8 that has been downloaded previously.

**Comment by jeaye** [comment]
I just pushed, tonight, a change: https://github.com/jeaye/color_coded/commit/8a205973c5032c50266414f4caa7e8f7ea06739e Will you see if that caused it?

**Comment by oblitum** [comment]
Will check.

**Comment by oblitum** [comment]
No, it was not that one.

**Comment by oblitum** [comment]
Will try to bisect.

**Comment by oblitum** [comment]
@jeaye it started after pull request #114 was merged. It's unrelated with the "strange behaviour" issue, I'm now using a `~/.color_coded` to evade it. This `:CCerror` message `/usr/include/wchar.h:39:11: fatal error: stdarg.h' file not found` just comes up, regardless of that, and highlighting in truth is not working. I've just bisected, didn't check why.

**Comment by oblitum** [comment]
I coudn't find exactly which commit of that pull was the culprit because while bisect I had to skip them because the build gets broken without them all applied.

**Comment by oblitum** [comment]
I've opened #126.

**Comment by oblitum** [comment]
by the way, as initially speculated in the beginning of this issue, the commit before and after the pull both are linking with liblua5.2, vim links to 5.3, and it's not being an issue, just by applying the `-fcolor-diagnostics` fix, later commits fixed the linking version, linking to 5.3.

**Comment by tony** [comment]
@oblitum what font is that in your screenshot?

**Comment by oblitum** [comment]
@tony https://github.com/powerline/fonts/tree/master/Monofur. I liked it very much when I found it, it missed the one variant which I've added there, it's the only place you find the 3, already patched for powerline.

**Comment by ZWindL** [comment]
@oblitum It's very good that can help you ;)
