### ISSUE TITLE
Pull #114 breaks highlighting

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#126]
Reason the highlighting is broken should be `:CCerror` -> `/usr/include/wchar.h:39:11: fatal error: stdarg.h' file not found`.

System: ArchLinux.

**Comment by alientechnology** [comment]
I had the same problem, but changing `.color_coded` by adding include directory as system helps as i can see for now. I mean change `-I/usr/include/c++/6/` to `-isystem/usr/include/c++/6/`, but of course with your paths.

**Comment by oblitum** [comment]
I'm not sure whether it's related, just pure speculation, but I recall clang having internal hardcoded paths to look for c++ libs (and headers maybe), relative to the clang installation.

**Comment by alientechnology** [comment]
Yes, it must has something to do with clang's builtin includes, i sepose.

**Comment by tony** [comment]
Is this still happening after 8a20597?

**Comment by oblitum** [comment]
@tony yes, if you follow #120, it was speculated as the problem, but it's not.

**Comment by ZWindL** [comment]
Yesterday Arch updated its clang package to 3.8, but the problem still exists.
And the error message is different than before.

**Comment by tony** [comment]
> And the error message is different than before.

Can you give the error message as well as the commands for cmake, output of cmake, output of make, etc?

**Comment by ZWindL** [comment]
@tony When I'm editting an new(empty) cpp file or something that doesn't use standard library, there's no error message, but if I type "#include <iostream>", or the other standard library was included in, the error message shows up(from ":CCerror") ->
>  error: expected unqualified-id
> error: source file is not valid UTF-8
> ...
> fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by tony** [comment]
@ZWindL: I would need more detail on your OS, vim version, what clang/llvm you're building against, etc.  Is it really truncated with ``...``? Is there anything else you can squeeze out of ``:messages``?

@oblitum I am confused, does this error still happen even after editing ``~/.clang_complete`` with @alientechnology's fix?  Is there any more information you can provide (CMake output, make output, OS, etc?)

My larger intention with (my part) of #114 was to clean out CMake and make it so using the system's/distros/sdk's provided clang headers was more seamless.

If its can't be figured out, I don't mind seeing it reverted, I've moved onto other things, unfortunately I've sunk a lot of time into this, along with other vim plugins and the whole vim plugin ecosystem suffers from a crippling lack of standards and diagnostic tools in the plugin community. Debugging vim plugins is already hard, vim plugins that work with lua and other languages even more so, forget trying to build and link a library against freaking clang.

Hmm, @jeaye : Is there any ability the library could have to dump more verbose debug logs / env information?

**Comment by oblitum** [comment]
@tony You mean `.color_coded`.

With an updated ArchLinux (which now in Clang 3.8):

- Without `-fcolor-diagnostics` and without `-isystem/usr/include/c++/6.1.1`: Issue #120/#118/#104.
- With `-fcolor-diagnostics` and without `-isystem/usr/include/c++/6.1.1`:  `:CCerror` gives `/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/cstdlib:75:15: fatal error: 'stdlib.h' file not found`
- With `-fcolor-diagnostics` and without `-isystem/usr/include/c++/6.1.1`: no issues.

**Comment by oblitum** [comment]
Even though I mention system's clang version, it's not what I use when building color_coded, I just use the bundled version.

**Comment by ZWindL** [comment]
@tony No, it's not really truncated with `...` just all rows are same as each other.
My OS is Arch Linux, all the packages are refresh.
My vim version infomation is [here](http://paste.ubuntu.com/16504069/)  (I'm using Chinese, so I there may have some Chinese letters)

**Comment by jeaye** [comment]
> Hmm, @jeaye : Is there any ability the library could have to dump more verbose debug logs / env information?

Quite possibly; what did you have in mind? color_coded doesn't track much with the environment and knows/cares almost nothing about the system on which it's running. Most of the debug logs in the source (which I keep in there, just commented) are for following the tokens generated from libclang.

@oblitum Thanks for the follow up; color_coded is currently using 3.8, if left to its own devices.

**Comment by ZWindL** [comment]
Well, my issue should blame a source code I write before. In a dir which was use to study C++ programing has a source code named "new.cpp" and it contains these code
```c++
#include <iostream>
#include <vector>
#include <cctype>

void abc_(int a, int b) {
        std::cout << a + b << std::endl;
        std::cout << "who are you" << std::endl;
        std::cout << "who are you" << std::endl;
}

void abc_(std::string str) {
        std::cout << str << std::endl;
}

int main()
{
        int a = 5, b = 4;
        std::string c("Hello World");
        c.size();
        abc_(a, b);
        std::vector<std::string> s;
        abc_(c);
        s.size();

        return 0;
}
```
And while I deleted the binary file compiled with it, the problem solved. `:CCerror` no more shows any error.

**Comment by oblitum** [comment]
I don't know what happened but by now on updated Arch even with:

- With -fcolor-diagnostics and with -isystem/usr/include/c++/6.1.1: highlighting is normal and :CCerror gives no issues.

I'm still getting `:CCerror -> /usr/include/wchar.h:39:11: fatal error: stdarg.h' file not found`.

**Comment by UnrealQuester** [comment]
Try including the gcc include directory. This should be something like `/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/`. The path may vary depending on your system and gcc version.

**Comment by oblitum** [comment]
Thanks @UnrealQuester, that fixed it.

**Comment by Hexcles** [comment]
FWIW, the missing header problem is mentioned in [YCM's FAQ](https://github.com/Valloric/YouCompleteMe#completion-doesnt-work-with-the-c-standard-library-headers) with some more details.

The solution mentioned by @UnrealQuester is just an example and the exact path should be modified according to your platform, and unfortunately, each time after g++ upgrades (because of the version number in the path).

**Comment by jeaye** [comment]
Thanks, @Hexcles. I've added in the same workaround for MacOS now. It seems that GNU/Linux users may need to add the GCC paths if they hit this, unless we try to spray and pray with the common paths.
