### ISSUE TITLE
CCerror: unknown compilation error, should provide more information if available

### ISSUE THREAD

**Issue by apilaszkiewicz** [jeaye/color_coded#127]
**problem**
`CCerror: unknown compilation error`

which was:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Vim: Caught deadly signal ABRT
Vim: Finished.`

**quick solution**: 
`LC_ALL=C gvim`

**proposed**
`CCerror: unknown compilation error` should provide more information if available.

**Comment by jeaye** [comment]
@Horosphere @apilaszkiewicz Please let me know if you have any issues with the extended error logging.
