### ISSUE TITLE
How can I get color_coded's compilation flags

### ISSUE THREAD

**Issue by 4pao** [jeaye/color_coded#130]
Recently I installed color_coded in my new Mac, but it has errors in CCerror. How can I get compilation flags when color_coded working?

/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:310:9: error: no member named 'fpcl
assify' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:311:9: error: no member named 'isfi
nite' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:312:9: error: no member named 'isin
f' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:313:9: error: no member named 'isna
n' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:314:9: error: no member named 'isno
rmal' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:315:9: error: no member named 'isgr
eater' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:316:9: error: no member named 'isgr
eaterequal' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:317:9: error: no member named 'isle
ss' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:318:9: error: no member named 'isle
ssequal' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:319:9: error: no member named 'isle
ssgreater' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:320:9: error: no member named 'isun
ordered' in the global namespace
/Users/caozhong/.vim_runtime/sources_non_forked/color_coded/build/clang+llvm-3.8.0-x86_64-apple-darwin/include/c++/v1/cmath:321:9: error: no member named 'isun
ordered' in the global namespace

**Comment by jeaye** [comment]
color_coded uses a small set of default flags which setup the include paths into the local clang, system directories, etc. They can be found here, as `pre_constants`, which are put before your flags, and `post_constants`, which are put after: https://github.com/jeaye/color_coded/blob/master/include/conf/defaults.hpp

Typically, you'll want to configure your project using its custom flags by editing the `.color_coded` file in your project's root directory, somewhere at or above Vim's working directory. Let me know if you continue to have issues with this.

**Comment by 4pao** [comment]
Still exist no matter there is one .color_coded or not. It quite weird since I can build normal app using the same clang in color_coded directory.

**Comment by jeaye** [comment]
You'll need to share a test case, with the `.color_coded` you used and the clang flags you used to compile the project.

**Comment by 4pao** [comment]
I think its more like my platform's problem. After I change to this new Macbook Pro 2015, the problem emerged.

This is the code source: https://github.com/BVLC/caffe.git

.color_coded:
"-x
c++
-DCAFFE_VERSION=1.0.0-rc3
-DCMAKE_BUILD
-DGTEST_USE_OWN_TR1_TUPLE
-DNDEBUG
-DUSE_LEVELDB
-DUSE_LMDB
-DUSE_OPENCV
-DWITH_PYTHON_LAYER
-Dcaffe_EXPORTS
-Dpycaffe_EXPORTS
-DUSE_GREENTEA
-I/Users/caozhong/Workspace/caffe/include
-I/Users/caozhong/Workspace/caffe/src
-I.build
-I.build/include
-Wall
-Wno-sign-compare
-Wno-uninitialized
-std=c++11
-isystem
/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers
-isystem
/Users/caozhong/Workspace/anaconda/include
-isystem
/Users/caozhong/Workspace/anaconda/include/python2.7
-isystem
/Users/caozhong/Workspace/anaconda/lib/python2.7/site-packages/numpy/core/include
-isystem
/Users/caozhong/Workspace/viennacl-dev
-isystem
/usr/local/include
-isystem
/usr/local/include/opencv
-isystem
/usr/include"

**Comment by jeaye** [comment]
Are you also using YCM with this project? Does it have any issues with
your code, and are the flags being used the same?

**Comment by 4pao** [comment]
Yes, I use YCM. A few benign warning, nothing erroneous and the flags are all generated by YCM-generator.

**Comment by jeaye** [comment]
Some excellent work has been merged, which should address this issue. Feel free to reopen if it comes back up.
