### ISSUE TITLE
clang cannot find some header files

### ISSUE THREAD

**Issue by Horosphere** [jeaye/color_coded#131]
When I run `:CCerror` on my cpp files, I get the message:

```
/usr/lib/gcc/.../c++/6.1.1/cstddef:50:10: fatal error: 'stddef.h' file not found
```

For some other files, it is `stdarg.h` file not found. I compiled with the `DOWNLOAD_CLANG` flag on but the problem presists with the flag off. I did not move the clang binary and the files `stddef.h` and `stdarg.h` reside in `/usr/include/clang/3.8/include`. Adding `-I/usr/include/clang/3.8/include` to `.color_coded` configuration file does not help.

**Comment by jeaye** [comment]
I've seen this issue before on OS X, if you're missing the command line
tools. If you're on OS X, please check the README how to install the
command line tools.

If not, please share more info about your environment.

**Comment by Horosphere** [comment]
@jeaye I am using Ubuntu and `apt-get install build-essential libclang-3.8-dev libncurses-dev libz-dev cmake xz-utils` says that all the libraries are in their newest versions. I have `GCC 6`

**Comment by jeaye** [comment]
Did you delete the extracted clang files after building?

**Comment by Horosphere** [comment]
No. I did not run `make clean` or `make clean_clang`. They seem to break `color_coded`

**Comment by jeaye** [comment]
My guess is that this has to do with a location change with GCC's
headers. Please investigate where those missing headers actually live on
your machine and try adding those paths to your `.color_coded`. It may
be that more default paths will be needed to support GCC6 out of the
box.

**Comment by Horosphere** [comment]
I found the `stddef.h` inside `/usr/lib/gcc/x86_64-linux-gnu/6/include`. After adding `-I/usr/lib/gcc/x86_64-linux-gnu/6/include` to `.color_coded`, it says `stdlib.h` file not found. This file lives in `/usr/include` but the error persists after adding that to the configuration.

**Comment by jeaye** [comment]
Try using `-isystem` instead of `-I`?

**Comment by Horosphere** [comment]
Thanks. The following worked for me:
```
-isystem
/usr/include/c++/6
-isystem
/usr/lib/gcc/x86_64-linux-gnu/6/include
```
I've found out two things:
1. Although `stdlib.h` also resides in `/usr/include`, I must include `/usr/include/c++/6` so clang can find it.
2. The fourth line can be replaced by `/usr/lib/llvm-3.8/lib/clang/3.8.0/include`. I think it is simply a symbolic link.

**Comment by librehat** [comment]
Neither works for me. I got complaints about either `stdarg.h` or `stdlib.h`. :(

**Comment by Hexcles** [comment]
I went through the code and found that the global default flags were supposed to work around precisely this issue, as long as the downloaded/prebuilt clang+llvm is used (which bundles all the headers we need already). Turns out there's a bug in that code and I've sent #145 to fix it.

**Comment by jeaye** [comment]
Right you are -- thanks!
