### ISSUE TITLE
Do not download clang again if it has already been downloaded

### ISSUE THREAD

**Issue by NotAFile** [jeaye/color_coded#134]
Currently, clang is re-downloaded and extracted every time cmake is run, even if clang has already been downloaded before.

**Comment by jeaye** [comment]
That's odd. Are you sure you're not deleting your build directory? I'm not able to reproduce this.

```bash
mkdir build; cd build
cmake ..
make install
cmake .. # You're saying it should download clang again here?
```

**Comment by jeaye** [comment]
Ah, I think I know what you're saying; you've deleted the tarball but kept the extracted directory and you don't want the tarball to be dowloaded again if the directory is there. Is that correct?

**Comment by NotAFile** [comment]
huh, weird, it's working now when I deliberately try to reproduce it. I must have overlooked something.
