### ISSUE TITLE
what is the minimum folders and files that should remain finally

### ISSUE THREAD

**Issue by gcwenken** [jeaye/color_coded#138]
After build successfully, there are a lot of files and folders in the .vim/bundle/color_coded. I want to ask which of them are actually needed finally. Compare to /usr/share/vim/vim74, I know after autoload colors plugin and color_coded.so are required. Are there any other files or folders that are required to run color_coded correctly. I am not quite familiar with the plugin system of vim and I want to save space of my home folder.

**Comment by jeaye** [comment]
You can run

```bash
git clean -fd
```

to remove untracked files. From there, you can remove the intermediate CMake files and the clang archive (which you'll need to download again on the next update, if deleted).

```bash
rm -rf ./CMakeFiles ./clang+llvm-3.8.0-*tar.xz
```

That should free up about 140MB.
