### ISSUE TITLE
lua headers not found when building on osx

### ISSUE THREAD

**Issue by sammcj** [jeaye/color_coded#14]
OSX 10.10.2
Lua 5.2.3

```
samm-mbp ~/.vim/bundle/color_coded % make                                                                                                                                                            git:master
Tracking API changes...

Building bin/libcolor_coded_boost_system.a
Linking bin/libcolor_coded_boost_system.a
Building bin/libcolor_coded_boost_filesystem.a
Linking bin/libcolor_coded_boost_filesystem.a
Building bin/color_coded.so
 Compiling src/main.cpp
src/main.cpp:3:12: fatal error: 'lua.h' file not found
  #include <lua.h>
           ^
1 error generated.
make: *** [src/main.cpp.o] Error 1
```

**Comment by jeaye** [comment]
Do you have macvim installed using brew and --with-lua?

**Comment by sammcj** [comment]
Thanks for your reply @jaeye, no I haven't installed macvim yet as the instruction to do so appears after the build - are the lua headers it's looking for included with macvim rather than lua itself?

I just went to install macvim, however it looks like there's a bug in the current version that prevents it from building - https://github.com/Homebrew/homebrew/issues/38047#issuecomment-88872142

**Comment by oblitum** [comment]
@sammcj with `brew install -vd` you can get detailed output of the building.

**Comment by jeaye** [comment]
On OS X, having lua present is required for the build. I can reorder the README instructions now to make this more clear. I'm not sure about that issue, since I have MacVim installed on Yosemite (using the default ruby). Lua is not included in MacVim, but it's a dependency which brew will resolve when you specify `--with-lua`.

**Comment by oblitum** [comment]
@sammcj ah yeah, this was my next question, whether you have lua installed by homebrew at `/usr/local`, with headers accessible for building executables with the compiler. Installing MacVim `--with-lua` would do it implicitly, but there's no explicit instruction regarding that.

**Comment by sammcj** [comment]
Yeah lua is installed to `/usr/local/bin/lua`, I'm thinking this might actually be an xcode linking issue - hold fire while I repair xcodes developer tools...

**Comment by sammcj** [comment]
If you'd like we can close this ticket as I think we've confirmed that the issue is with macvim compilation and not color_coded itself?

**Comment by jeaye** [comment]
Ok. I've updated the instructions to show that macvim needs to come first on OS X. If it turns out color_coded has issues for you, please reopen this guy or open a new ticket!

**Comment by sammcj** [comment]
Perfect, thank you.

Just fixed it, sure enough, reinstalled xcode dev tools fixed it:

```
xcode-select --install
# Complained about permissions of one file so had to change ownership as such:
sudo chown root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/dyld_sim
```

**Comment by jeaye** [comment]
Excellent! Thanks for the update; I'm glad things are working well now.

**Comment by shi-314** [comment]
I am getting the same error on Linux Mint: 
```
>make
Tracking API changes...

Building bin/libcolor_coded_boost_system.a
 Compiling src/error_code.cpp
Linking bin/libcolor_coded_boost_system.a
Building bin/libcolor_coded_boost_filesystem.a
 Compiling src/codecvt_error_category.cpp
 Compiling src/operations.cpp
 Compiling src/path.cpp
 Compiling src/path_traits.cpp
 Compiling src/portability.cpp
 Compiling src/unique_path.cpp
 Compiling src/utf8_codecvt_facet.cpp
Linking bin/libcolor_coded_boost_filesystem.a
Building bin/color_coded.so
 Compiling src/main.cpp
src/main.cpp:3:19: fatal error: lua.h: No such file or directory
   #include <lua.h>
                   ^
compilation terminated.
make: *** [src/main.cpp.o] Error 1
```

I have also installed lua and lua-dev
```
sudo apt-get install lua5.2 lua5.2-dev
```

Any ideas?

**Comment by jeaye** [comment]
On Thu, Apr 02, 2015 at 06:49:53AM -0700, Shivan Taher wrote:
>    I am getting the same error on Linux Mint:
> 
>    I have also installed lua and lua-dev
> 
>  sudo apt-get install lua5.2 lua5.2-dev
> 
>    Any ideas?

First, check where `lua.h` is installed. If it's not in a standard system header location, the compiler isn't going to find it. It should be around `/usr/local/include` or `/usr/include`.

**Comment by shi-314** [comment]
Ok thanks it was installed in ```/usr/include/lua5.2/```. But I get some compilation errors now:
```
Compiling src/main.cpp
In file included from include/clang/translation_unit.hpp:6:0,
                 from include/clang/token_pack.hpp:5,
                 from include/core.hpp:4,
                 from include/events.hpp:3,
                 from src/main.cpp:8:
include/detail/util.hpp:11:16: error: ‘decay_t’ is not a member of ‘std’
     std::array<std::decay_t<T>, sizeof...(Ts) + 1> constexpr
                ^
include/detail/util.hpp:11:16: error: ‘decay_t’ is not a member of ‘std’
include/detail/util.hpp:11:30: error: wrong number of template arguments (1, should be 2)
     std::array<std::decay_t<T>, sizeof...(Ts) + 1> constexpr
```

Isn't it supposed to be ```std::decay```?

**Comment by oblitum** [comment]
> Isn't it supposed to be `std::decay`?

Most, if not all, `_t` things are part of C++14.

**Comment by jeaye** [comment]
On Thu, Apr 02, 2015 at 07:45:50AM -0700, Shivan Taher wrote:
>    Isn't it supposed to be std::decay?

No. :) Your compiler (or standard lib) version doesn't meet the requirement, it seems. Check the dependencies section of the README to see what's required. If you do meet the requirements and you're still seeing issues, let me know.

**Comment by shi-314** [comment]
Of cource! I didn't know that C++14 is already a thing - just got used to C++11 :sweat_smile:
