### ISSUE TITLE
color_coded appears to turn off vim's spell option

### ISSUE THREAD

**Issue by CookiesBestDinner** [jeaye/color_coded#143]
with a vimrc of:

``` vim
filetype plugin indent on
set spell
```

Opening a .cpp file and entering `:set spell?` results in the message`nospell`
I expected the message to instead have been `spell` which I had set in my vimrc
Disabling color_coded makes `:set spell?` show `spell`

I don't see any explanation of this when grepping color_coded's root directory for "spell"

Tested with a clean .vim (cloned color_coded into .vim and built it) and the above .vimrc with vim 8.0.13 on arch linux, I'm seeing the same thing on my laptop that's running vim 7.4.1868 on fedora 24, but did not try a clean .vim there.

I'm not seeing spell being turned off when running vim with:

`vim -V9myVimLog`

But from when I check the status of the spell option it says:

```
nospell
    Last set from ~/.vimrc
```

Which is odd, since when I set it in that file, it was to "spell", not "nospell"

I'm so very far out of my debugging league here, I could be missing any number of obvious explanations

**Comment by UnrealQuester** [comment]
This seems to stem from our use of `ownsyntax` to set the color_coded syntax for the current window. According to the vim docs, this also resets all `spell` options set for whatever reason.

**Comment by jeaye** [comment]
@CookiesBestDinner Please let me know if this still happens for you. I've put in a fix and verified it locally.

**Comment by jeaye** [comment]
@UnrealQuester Thanks for identifying the cause. :)

**Comment by CookiesBestDinner** [comment]
Those poorly spelled comments will hide no more! :>
