### ISSUE TITLE
Install Broken for Arch Linux

### ISSUE THREAD

**Issue by Cyberdr8gon** [jeaye/color_coded#144]
In cmake/LLVM.cmake on line 135, the regex complains it needs at least 5 arguments.

It _seems_ as though install is broken because it assumes a non-distributed llvm install. However, on archlinux, it is embeded in the system /usr/bin /usr/lib etc. and it doesn't support this configuration for a variety of reasons. Also, the clang binary download doesn't work on Arch Linux as well, the same failing to find llvm 

The failing macro is llvm_set_libs

**Comment by jeaye** [comment]
I can reproduce this in an Arch vm; looking into it. Let me know if you arrive at any solutions in the meantime.

**Comment by jeaye** [comment]
Ah, looks like it's been addressed here: https://github.com/Valloric/YouCompleteMe/issues/778

**Comment by jeaye** [comment]
@Cyberdr8gon Alrighty, it's working for me now. Care to give it a go and let me know before I close this?

**Comment by Cyberdr8gon** [comment]
It is fixed, thank you. Good idea to use the opensuse libclang!!!

**Comment by jeaye** [comment]
Good to hear; thanks for reporting this.
