### ISSUE TITLE
conflict with indentLine

### ISSUE THREAD

**Issue by innoink** [jeaye/color_coded#147]
when use color_coded, indentLine will disapper

**Comment by UnrealQuester** [comment]
This seems related to #143, as we use `ownsyntax` to set the color_coded syntax highlighting for the current window. If you reload the file with `:e`, the indent lines will appear again.

**Comment by jeaye** [comment]
@innoink #143 has since been fixed and closed; is this still an issue for you? I'm not familiar with `indentLine` and I'm guesing you're talking about this plugin: https://github.com/Yggdroot/indentLine Is that right?

**Comment by UnrealQuester** [comment]
Looks like the issue has not been fixed. indentLine changes the syntax highlighting which also gets reset when we use `ownsyntax`.

This is not something we can or should fix on our end. indentLine needs to wait for the `Syntax` autocmd and reapply its highlighting.

Can you try out the pull request I send to indentLine and see if this works for you?

**Comment by jeaye** [comment]
@UnrealQuester Yep, that fixes it for me. I'll close this ticket and @innoink can hopefully chime in on that PR, to help get it merged.

Awesome work, man. Thanks.
