### ISSUE TITLE
build with clang-4.0 cause leading or trailing whitespace problem in cmake

### ISSUE THREAD

**Issue by gcwenken** [jeaye/color_coded#149]
I try to build the library with clang-4.0 in ubuntu, the cmake is in version 3.7.1

the build command:
cmake .. -DLLVM_CONFIG=/usr/bin/llvm-config-4.0 -DDOWNLOAD_CLANG=0

the output:
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found 64bit system
-- Updating submodules
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Performing Test COMPILER_SUPPORTS_CXX1Y
-- Performing Test COMPILER_SUPPORTS_CXX1Y - Success
-- Looking for Lua
-- Found Lua
--   Lua include /usr/include/lua5.2
--   Lua lib /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found LLVM: /usr/lib/llvm-4.0 (found version "4.0.0") 
-- Detected that llvm-config comes from a build-tree, adding more include directories for Clang
-- Found Clang (LLVM version: 4.0.0)
--   Include dirs:       /usr/lib/llvm-4.0/include;/tools/clang/include;/tools/clang/include
--   Clang libraries:    /usr/lib/llvm-4.0/lib/libclang.so;/usr/lib/llvm-4.0/lib/libclangTooling.a;/usr/lib/llvm-4.0/lib/libclangToolingCore.a;/usr/lib/llvm-4.0/lib/libclangIndex.a;/usr/lib/llvm-4.0/lib/libclangFrontend.a;/usr/lib/llvm-4.0/lib/libclangFrontendTool.a;/usr/lib/llvm-4.0/lib/libclangDriver.a;/usr/lib/llvm-4.0/lib/libclangFormat.a;/usr/lib/llvm-4.0/lib/libclangCodeGen.a;/usr/lib/llvm-4.0/lib/libclangParse.a;/usr/lib/llvm-4.0/lib/libclangSema.a;/usr/lib/llvm-4.0/lib/libclangEdit.a;/usr/lib/llvm-4.0/lib/libclangAnalysis.a;/usr/lib/llvm-4.0/lib/libclangSerialization.a;/usr/lib/llvm-4.0/lib/libclangStaticAnalyzerFrontend.a;/usr/lib/llvm-4.0/lib/libclangStaticAnalyzerCheckers.a;/usr/lib/llvm-4.0/lib/libclangStaticAnalyzerCore.a;/usr/lib/llvm-4.0/lib/libclangRewriteFrontend.a;/usr/lib/llvm-4.0/lib/libclangRewrite.a;/usr/lib/llvm-4.0/lib/libclangAnalysis.a;/usr/lib/llvm-4.0/lib/libclangAST.a;/usr/lib/llvm-4.0/lib/libclangASTMatchers.a;/usr/lib/llvm-4.0/lib/libclangDynamicASTMatchers.a;/usr/lib/llvm-4.0/lib/libclangLex.a;/usr/lib/llvm-4.0/lib/libclangBasic.a
--   Libclang C library: /usr/lib/llvm-4.0/lib/libclang.so
-- Generating sources
-- Checking for luajit
-- Configuring done
CMake Error at CMakeLists.txt:85 (add_library):
  Target "color_coded" links to item "-L/usr/lib/llvm-4.0/lib " which has
  leading or trailing whitespace.  This is now an error according to policy
  CMP0004.

-- Generating done
-- Build files have been written to: /home/ken/Downloads/color_coded-master/build

it seem that CMakeLists.txt:85 (add_library) need more command to remove leading or trailing whitespace.

**Comment by UnrealQuester** [comment]
Try rebuilding the entire project by deleting the build directory or all CMake generated files and then running cmake again.

**Comment by gcwenken** [comment]
I already try to delete the build directory and rebuild the entire project a lot of time. The problem is if I try to build the library with clang-4.0, there is a whitespace at the end of "-L/usr/lib/llvm-4.0/lib ". If I try to build the library with clang-3.9, that is:
cmake .. -DLLVM_CONFIG=/usr/bin/llvm-config-3.9 -DDOWNLOAD_CLANG=0
there is no such problem. The source code must be modified to use STRIP to clear the trailing white spaces.

**Comment by jeaye** [comment]
This has been fixed by #150. Note that @UnrealQuester mentioned that LLVM 4.0 still won't work with color_coded, since the API of the compilation database has changed.

Thanks, to both of you, for identifying and fixing this issue.
