### ISSUE TITLE
Compilation Error in ubuntu 16.04

### ISSUE THREAD

**Issue by VincentVonPark** [jeaye/color_coded#167]
HI guys, Thank for making it out and working well.

On compiling it, I am lost so Could you help me out ?

## Circumstance
- Ubuntu 16.04
- Lua
  5.2 and friends
- Clang 5.0 installed by "sudo snaptic"

## The Modifed 
i use ubuntu 16.04 so that I changed 
 - 14.04 to 16.04 in download.cmake 
 - change SHA256 value  because of difference file for 16.04

```
      set(CLANG_DIRNAME "clang+llvm-${CLANG_VERSION}-linux-x86_64-ubuntu16.04")
      set(CLANG_SHA256 "171968549a12d8cf1e308004a1c31450f663359731e1524b952665f80149284b")

```
 
## Error shows it below 
```
CMakeFiles/color_coded_config_test.dir/test/src/config/main.cpp.o:

 In function `color_coded::conf::load_compilation_database(std::string const&, boost::filesystem::path)':
main.cpp:(.text._ZN11color_coded4conf25load_compilation_databaseERKSsN5boost10filesystem4pathE[_ZN11color_coded4conf25load_compilation_databaseERKSsN5boost10filesystem4pathE]+0x83): undefined reference to `clang::tooling::JSONCompilationDatabase::loadFromFile(llvm::StringRef, std::string&, clang::tooling::JSONCommandLineSyntax)'
collect2: error: ld returned 1 exit status
CMakeFiles/color_coded_config_test.dir/build.make:139: recipe for target 'color_coded_config_test' failed
make[2]: *** [color_coded_config_test] Error 1
CMakeFiles/Makefile2:238: recipe for target 'CMakeFiles/color_coded_config_test.dir/all' failed
make[1]: *** [CMakeFiles/color_coded_config_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you so much to read it

Vincent Van Park.

**Comment by jeaye** [comment]
@VincentVonPark Thanks for reporting your issue; hopefully we can get it quickly resolved.

First and foremost, why are you changing the CMake file to download a different clang version? You may be on 16.04, but the 14.04 version should work as well. Did you originally try without modification and run into some other issue? If so, that's likely the issue we should be discussing.

**Comment by VincentVonPark** [comment]
Hi the Author, I am Not a troublemaker,

I just want to follow the right way as I think because of meeting the same version because I have been trouble using the ubuntu as the times goes by, and I want to know what is causing the side effect, 
For finding the way  I follow the step by step from the Youcompleteme with full install Not easy one.
 
I installed the  clang-4.0 which is not recommended version on the side of Ubuntu 16.04, and I just want to use more high version. For the matching version of two plug-ins of the vim. 
So i choose the version of clang-4.0 modified in download.cmake, and I got failed 
So I started to dig in...., I am lost...

That is why I am wringing to you, Sorry to bother you.

Could you answer me is there different from between 14.04 and 16.04 ?

Thank you so much for reading the article.

Vincent Van Park.

**Comment by jeaye** [comment]
You should be able to use color_coded, without modification, on Ubuntu 16.04. Just follow the installation steps in the readme. In short, install all the necessary dependencies with `apt`, add the plugin to your plugin manager so it will clone the repository, and `cmake . && make install` in the cloned directory.

When you follow the process laid out in the readme, without modifying anything, what issues do you run into?

**Comment by VincentVonPark** [comment]
Hi, the author,  

Thank you for guiding me and good advice.

I will follow you.

Vincent Van Park.

**Comment by jeaye** [comment]
Any update @VincentVonPark? If this is no longer an issue, I'd like to close the ticket.

**Comment by VincentVonPark** [comment]
No update,  I succeed it after original one, working well.
Please close the ticket

**Comment by jeaye** [comment]
Ok, great!
