### ISSUE TITLE
Background of highlighted elements doesn't respect cursorline background changes

### ISSUE THREAD

**Issue by skystrife** [jeaye/color_coded#17]
This is most easily explained with a screenshot:

![screenshot_2015-04-02_11-41-44](https://cloud.githubusercontent.com/assets/1378336/6968562/5b132ae8-d92d-11e4-8a59-52efc64e3e72.png)

My cursorline is a lighter background, but the tokens that have been highlighted are set to the "real" background.

**Comment by oblitum** [comment]
ah, this is what I mentioned here: https://github.com/jeaye/color_coded/issues/8#issuecomment-87474316.

**Comment by skystrife** [comment]
OK, based on that thread I found that indeed my theme is defining background colors for the things that color_coded is linking to. This doesn't cause a problem with *ordinary* highlighting colorschemes and such since the cursorline has higher priority than the rest, but since color_coded's syntax setup comes afterwards it has higher priority than cursorline.

I guess it's up to @jeaye to decide whether this is a bug with the theme or with color_coded. It could be fixed in either location (but I think a fix in color_coded might be better, since I can easily see theme writers saying "well this isn't a bug with the theme, it's something that your plugin is doing").

**Comment by jeaye** [comment]
@skystrife I'll need to see your color scheme. color_coded doesn't do the actual highlighting, it just tells vim which tokens use which highlighting groups. The background of the highlighting is based entirely on the highlighting groups, which, unless you're using the colorscheme shipped with color_coded (twilighted), should not be affected by color_coded.

**Comment by skystrife** [comment]
https://github.com/chriskempson/base16-vim/blob/master/colors/base16-monokai.vim

I think the problem is because the new highlighting groups are added after the syntax step, they have higher priority than the other rules (including cursorline), but I could be wrong...

**Comment by jeaye** [comment]
To quote the vim docs on `matchadd` and priority

> Syntax highlighting (see 'syntax') is a separate
> mechanism, and regardless of the chosen priority a match will
> always overrule syntax highlighting.

It looks like color_coded doesn't have a choice but to overrule here. If I can find anything else saying otherwise, I'll let you know, but it seems like the colorschemes need to remove the `bg` and `guibg` from the color_coded groups if they're highlighting the active line.

**Comment by jeaye** [comment]
I'm closing this, since I don't see that there's anything color_coded can do to help in this situation. If any better information can be found, we can reopen it.
