### ISSUE TITLE
Plugin prevents vim from starting

### ISSUE THREAD

**Issue by lemarquois** [jeaye/color_coded#175]
Hi,

I'm trying to take this plugin on my raspberry pi into operation.
I followed the installation to build and enabled the plugin in my .vimrc:

`Plugin 'jeaye/color_coded'`

Unfortunately my vim stopped working now:

```
pi@raspberrypi:~ $ vim ~/.vimrc
: CommandLine Error: Option 'view-background' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
Any ideas what I did wrong?

**Comment by lemarquois** [comment]
I followed this instruction:
```
cd ~/.vim/bundle/color_coded
rm -f CMakeCache.txt
mkdir build && cd build
cmake .. -DDOWNLOAD_CLANG=0
make && make install # Compiling with GCC is preferred, ironically
# Clang works on OS X, but has mixed success on Linux and the BSDs

# Cleanup afterward; frees several hundred megabytes
make clean && make clean_clang
```

But I did not download clang (this did not work on my platform).

**Comment by UnrealQuester** [comment]
I am asuming you are running Raspbian stretch. I tried to repdroduce the error on a debian stretch install and did not encounter any errors.

What llvm version are you using instead of the bundled version?

**Comment by lemarquois** [comment]
I have this version:

```
pi@raspberrypi:~/NimbusUserland/build $ clang --version
clang version 3.8.1-24+rpi1 (tags/RELEASE_381/final)
Target: armv6--linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin

```

**Comment by UnrealQuester** [comment]
Try updating llvm to 3.9 if possible. You probably need `libclang-3.9-dev` and `llvm-3.9`. Make sure to delete and remake the build directory to ensure cmake picks up the new version.

Alternatively we just added llvm 7 as the new default. Maybe that works for you.

**Comment by lemarquois** [comment]
Cool. Using version 3.9 solved my problem. Thanks.
