### ISSUE TITLE
Problems with installation on Windows

### ISSUE THREAD

**Issue by ashrasmun** [jeaye/color_coded#189]
Hello,

I'm trying to install build your software on Windows 10. I needed to change the compile flags in `cxx14.cmake` from `-std=c++14` to `/std:c++14` format to get past that point of installation, but now I'm stuck with Lua :( I had the precompiled lua binaries - they weren't recognized. I installed Lua using this link (http://lua-users.org/wiki/BuildingLuaInWindowsForNewbies) and they are still not recognized. I can use Lua inside command line and the path to .exe / .dll is in PATH. What am I doing wrong?

Kind Regards

**Comment by andrejlevkovitch** [comment]
@ashrasmun 

> I needed to change the compile flags in cxx14.cmake from -std=c++14 to /std:c++14

Do you try build with `vc`? What compiler you used for compile lua? I see that in manual uses `gcc`, so you can not build this library with `vc` - you can build it only with `gcc` or `clang`.

Also how I can see in [readme](https://github.com/jeaye/color_coded/blob/master/README.md) it is not supported for windows. So it can be very difficult... At first you need set directory with lua package (directory with `include` and `lib` folders). How I can [see](https://github.com/jeaye/color_coded/blob/master/cmake/FindLua.cmake) you must set `LUA_DIR` environment variable that points to needed directory.

**Comment by andrejlevkovitch** [comment]
@ashrasmun Also note that you need vim with lua support.

**Comment by ashrasmun** [comment]
@andrejlevkovitch I'm building it with MSVC. I see that there's no installation instruction for Windows, but I kind of hoped that if it doesn't explicitly state that, there's a change to make it work for that platform. I have Vim with `+lua/dyn` option, so I guess I just need to specify the lua location with some variable in my `.vimrc`.

I'll try to make it work with the tips provided. Thanks!

**Comment by ashrasmun** [comment]
Unfortunatelly after I've set the `luadll` variable in my vimrc to point to appropriate dll and also set `LIB_LIBRARIES` and `LIB_INCLUDE_DIR` variables, I still can't get it to work. I know that these two are most probably not environment variables, but I just try to make it work... I get the error:

-- Looking for Lua
CMake Error at cmake/lua.cmake:4 (message):
  Lua was not found but is required
Call Stack (most recent call first):
  CMakeLists.txt:41 (include)

**Comment by andrejlevkovitch** [comment]
@ashrasmun did you set `LUA_DIR` variable?

**Comment by ashrasmun** [comment]
@andrejlevkovitch  Yes, and it points to the directory in which I have the `include` and `bin` directories.

**Comment by andrejlevkovitch** [comment]
@ashrasmun cmake try find lua library in lib directory, so you should change `lib` to `bin` in file cmake/FindLua.cmake. And NOTE: lua, this module and vim must be builded bu same compiler.

**Comment by andrejlevkovitch** [comment]
@ashrasmun did you build the module?

**Comment by ashrasmun** [comment]
I couldn't get Lua to work. Also, as an experiment, I commented out the if statement in lua.cmake to see what will happen and it broke on the very next step, informing me that I need "curses". I think I'm done, I will try something else. Sorry for taking your time...

**Comment by andrejlevkovitch** [comment]
@ashrasmun i didn`t understand why you need curses - this program not required it. Anyway, I can recomend other program for c/c++ syntax colorizing. It don't required lua and has two parts: [client](github.com/andrejlevkovitch/vim-hl-server) and [server](github.com/andrejlevkovitch/hl-server). Also see #187 issue. This is a test program and Idid not build it under windows, but, I think, this must be simpler.
