### ISSUE TITLE
Installing using Vundle 

### ISSUE THREAD

**Issue by gzqx** [jeaye/color_coded#192]
Fedora 32. After installing using Vundle it alerts that it nees to be compiled (am I getting the readme wrong? I feel like it indicates that vundle can handle it automatically).

**Comment by jeaye** [comment]
Seems like Vundle failed to compile it automatically. What happens if you cd into that directory and try this? https://github.com/jeaye/color_coded#all

**Comment by gzqx** [comment]
step `cmake ..` gives error as
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCurses.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:44 (find_package)
```

**Comment by jeaye** [comment]
There we go. Please install ncurses, as well as your distro's versions of these deps: https://github.com/jeaye/color_coded#ubuntudebian

**Comment by gzqx** [comment]
This solves the question. In case someone is interested, on Fedora 32 (seems to be since 30), simply installing `ncurses-devel` is not enough, and `sudo dnf install ncurses-compat-libs`
