### ISSUE TITLE
Function parameters in argument list colored gray. Can it be changed?

### ISSUE THREAD

**Issue by kanaanayt** [jeaye/color_coded#194]
Can I change this? The color? From gray to something else? The parameters in the argument list as well as in the code below the function definition is gray and I'm wondering if I can change that.

**Comment by andrejlevkovitch** [comment]
See [highlight config](after/syntax/color_coded.vim)

**Comment by jeaye** [comment]
Yep, as @andrejlevkovitch said, check out the highlighting here: https://github.com/jeaye/color_coded/blob/master/after/syntax/color_coded.vim

There's also the sample colorscheme, twighlighted, here: https://github.com/jeaye/color_coded/blob/master/colors/twilighted.vim

In the case of function params, what you want is likely `ParmDecl`, which is highlighted to be the same a `Variable` here: https://github.com/jeaye/color_coded/blob/master/after/syntax/color_coded.vim#L17

To see the twighlighted coloring for `Variable`, you can look here: https://github.com/jeaye/color_coded/blob/master/colors/twilighted.vim#L55

You can add colors for those color_coded-specific bits to your vim config using something like:

```viml
" Add a hook to patch the colorscheme
function! FixColorscheme()
  hi Member guifg='.s:cyan .' guibg='.s:darkgrey .' gui=italic
  hi Variable guifg='.s:light_grey_blue .' guibg='.s:darkgrey .' gui=none
  hi Namespace guifg='.s:red .' guibg='.s:darkgrey .' gui=none
  hi EnumConstant guifg='.s:lightgreen .' guibg='.s:darkgrey .' gui=none
endfunction

augroup fix_colorscheme
  au!
  au ColorScheme * call FixColorscheme()
augroup END
```

**Comment by kanaanayt** [comment]
The types and their corresponding variable names tend to have the same color. 
Look at the following examples in yellow and in blue: 
string col2 
and 
string col3
I'm wondering if the type could be its own separate color.
<img width="1108" alt="Screen Shot 2020-11-26 at 6 37 13 PM" src="https://user-images.githubusercontent.com/10635782/100375420-6e20f700-3016-11eb-91a0-3caf60d32866.png">

**Comment by jeaye** [comment]
@kanaanayt Try switching to the twighlighted colorscheme. `:color twightlighted` and see if that's still the case. It shouldn't be.
