### ISSUE TITLE
Should not attempt to download when DOWNLOAD_CLANG=OFF and llvm was not found.

### ISSUE THREAD

**Issue by toluschr** [jeaye/color_coded#195]
I suggest the following change
```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -54,7 +54,7 @@ if (NOT DOWNLOAD_CLANG)
 	if(LLVM_FOUND)
 	  find_package(LibClang)
 	else()
-	  message(STATUS "LLVM not found on system")
+	  message(FATAL_ERROR "LLVM not found on system")
 	endif()
 endif()
```

**Comment by jeaye** [comment]
Seems sensible. Are you interested in making a PR, or would you like me to make the change?

Note that color_coded is currently being rewritten entirely and this patch won't affect the new version, but there's not specific timeline on that, so I think it makes sense to get this into master.
