### ISSUE TITLE
No change in gruvbox

### ISSUE THREAD

**Issue by shipleyxie** [jeaye/color_coded#197]
I use gruvbox color shceme, and add want to ad color_coded, after compile and install , I can't see any changes.
Is this a Bug?

**Comment by jeaye** [comment]
You'll want to check the `:CCerror` output and also make sure you've added the appropriate highlighting to your gruvbox theme. Docs for that are here: https://github.com/jeaye/color_coded#highlighting

**Comment by shipleyxie** [comment]
after cmake .. && make && make install ,
i got follwing message when typing :CCerror

> internal error: locale::facet::_S_create_c_locale name not valid
do you have any idea to solve this?

**Comment by shipleyxie** [comment]
> after cmake .. && make && make install ,
> i got follwing message when typing :CCerror in an opened .cpp file
> 
> > internal error: locale::facet::_S_create_c_locale name not valid
> 
> do you have any idea to solve this?

change let $LANG='en'  to  let $LANG='en_US.UTF-8' solve this probelm.
Now color_coded works fine in my vim
