### ISSUE TITLE
luajit causes instability; crashes on startup

### ISSUE THREAD

**Issue by jeaye** [jeaye/color_coded#20]
Currently, it's best to use color_coded with vim when luajit is not installed. Having it installed has shown to be problematic, mainly causing segfaults at startup.

**Comment by Congee** [comment]
Neither Homebrewed vim.

**Comment by jeaye** [comment]
What? Macvim through homebrew works fine if you follow the steps outlined in the readme. If you're having specific issues, please first make sure you've followed the readme, then describe them.

**Comment by Congee** [comment]
@jeaya sorry for unclear words. I meant the vim I use is `brew install vim` rather than `macvim`.
And I've installed color_coded by following steps stated in README.

It works fine, after unlinking luajit and recompiling vim, except that the highlighting delays after launching, but it's another question.

**Comment by jeaye** [comment]
The delay you're seeing is likely just due to clang compiling your code. color_coded can't highlight any faster than clang can compile. Moving the cursor around will help make sure you see the update as soon as it's ready.

**Comment by Congee** [comment]
Thank you very much. : )

**Comment by jeaye** [comment]
Apparently this is also an issue on Linux, as shown by #26.

**Comment by jeaye** [comment]
Looks like this is not going to happen: https://www.freelists.org/post/luajit/OSx-load-luajit-64bit-from-plugin

luajit may work on some platforms, but it can't reliably work on all platforms supported by color_coded, so I'm not interested in supporting it. I'll close this and update the README. :(
