### ISSUE TITLE
Move to a more flexible and portable build system

### ISSUE THREAD

**Issue by jeaye** [jeaye/color_coded#25]
They all suck, looks like I'll be putting in CMake.

**Comment by jeaye** [comment]
@oblitum Are you available to test the `cmake` branch? It has updated install instructions. Ideally, we test in fresh directories (not existing color_coded installation) and on Linux and OS X. I've given it a go on OS X and Arch Linux and I'll do Ubuntu tomorrow. If you can, let me know how it goes and what you were able to test.

**Comment by oblitum** [comment]
@jeaye only when I get back home late.

**Comment by jeaye** [comment]
No problem. At your convenience!

**Comment by jeaye** [comment]
I have tested this on OS X, Arch Linux, and Ubuntu. Everything is working nicely. @tony, @oblitum, if you have a chance to test on any UNIX-based platform, please do. I'd like to merge this ASAP.

**Comment by HappyCerberus** [comment]
cmake still succeeds, even when compiler does not support C++14

**Comment by jeaye** [comment]
That's superbly mysterious. Mind giving me the full CMake log output? @HappyCerberus

**Comment by jeaye** [comment]
To clarify, if I disable C++14 and just add the C++11 flags, it certainly does not compile (and for good reason -- I'm using generic lambdas and the library extensions from C++14, along with auto return types).

**Comment by HappyCerberus** [comment]
Well, the cmake serves the role of a configure, so the cmake itself should fail if the preconditions for the build are not met.

    -- Looking for Lua 5.2
    -- Found Lua
    -- Locating trusted Clang/LLVM 3.6.0
    -- Found clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    -- Clang/LLVM 3.6.0 already extracted
    -- Generating sources
    -- Configuring done
    You have changed variables that require your cache to be deleted.
    Configure will be re-run and you may have to reset some variables.
    The following variables have changed:
    CMAKE_C_COMPILER= /usr/bin/clang
    CMAKE_CXX_COMPILER= /usr/bin/c++

    -- The C compiler identification is Clang 3.5.0
    -- The CXX compiler identification is GNU 4.8.3
    -- Check for working C compiler: /usr/bin/clang
    -- Check for working C compiler: /usr/bin/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Performing Test COMPILER_SUPPORTS_CXX14
    -- Performing Test COMPILER_SUPPORTS_CXX14 - Failed
    -- Performing Test COMPILER_SUPPORTS_CXX1Y
    -- Performing Test COMPILER_SUPPORTS_CXX1Y - Success
    -- Looking for Lua 5.2
    -- Looking for Lua 5.1
    -- Found Lua
    -- Looking for cbreak in /usr/lib64/libncurses.so
    -- Looking for cbreak in /usr/lib64/libncurses.so - found
    -- Found Curses: /usr/lib64/libncurses.so
    -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8")
    -- Locating trusted Clang/LLVM 3.6.0
    -- Found clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    -- Clang/LLVM 3.6.0 already extracted
    -- Generating sources
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/simon/DOTFILES/vim/bundle/color_coded

**Comment by jeaye** [comment]
@HappyCerberus Your compiler *does* support C++14, hence why CMake didn't fail hard. There are two checks: first for `-std=c++14`, next for `-std=c++1y`. Are you saying you had an issue while building? Everything I see went perfectly fine.

**Comment by HappyCerberus** [comment]
Well, you are using C++14 library features. So yes, it failed in the build afterwards.

**Comment by HappyCerberus** [comment]
Btw, it doesn't compile well under GCC at all. Clang as few small issues (`::gets` declaration that should be marked as deprecated but isn't in the system headers and a missing `decay_t`), but GCC has big trouble compiling this code.

I'm pretty busy right now, but if I remember I will try to massage your code into working with GCC over the weekend.

**Comment by jeaye** [comment]
It absolutely does compile with GCC, assuming you're using the dependencies outlined in the README. Assuming you follow the outlined steps, this is working on OS X (Yosemite), Ubuntu 14.04, and Arch Linux (maybe others). Please ensure you've read through the README; in particular, make sure you have GCC 4.9 or higher.

If you're on an OS/distro which is not specified in the README, please detail that to me and I'll see how reasonable it is for you to get proper C++14 support. So far, it's already there on OS X and Arch and it's only a couple of commands away on Ubuntu and its derivatives.

**Comment by jeaye** [comment]
If it turns out to be an issue on your platform, we can consider downgrading to C++11. So far, it's not been a big issue on any supported platforms.

**Comment by oblitum** [comment]
@jeaye I've tested on OS X by now, and it worked ok and so far compilation went fine. I have one question:

- I've built it on `build` directory with `cmake ..` and `make`, after such steps I've just ended up with a compiled library in the `build` directory, will a make install put it in the right place of the plugin/src directory? With YCM's `make` step after a cmake it puts the lib at the right place for example.

**Comment by jeaye** [comment]
On Wed, Apr 08, 2015 at 06:30:59AM -0700, Francisco Lopes wrote:
>      • I've built it on build directory with cmake .. and make, after such
>        steps I've just ended up with a compiled library in the build
>        directory, will a make install put it in the right place of the
>        plugin/src directory? With YCM's make step after a cmake it puts the
>        lib at the right place for example.

Yup. Installation is relative to the source directory, not the build directory. Thanks for reporting back about your success with OS X.

**Comment by oblitum** [comment]
It's all ok then. Regarding the c++14, just opinion, I would be forcing people to have to have it =D and maintain my codebase pretty.

**Comment by jeaye** [comment]
On Wed, Apr 08, 2015 at 06:55:54AM -0700, Francisco Lopes wrote:
>    It's all ok then. Regarding the c++14, just opinion, I would be forcing
>    people to have to have it =D and maintain my codebase pretty.

Absolutely. Unless it turns out to be a big blocker (hasn't so far), it's staying. Thanks for your opinion. If you are able to test color_coded with cmake on any other platforms, let me know.

**Comment by oblitum** [comment]
@jeaye ah, anyway I don't believe it's specifically related with cmake but I just got a libclang parsing crash opening some c++ file that I could open fine before.

**Comment by tony** [comment]
I'll test this on freebsd current later today

**Comment by jeaye** [comment]
@oblitum Uh oh. Is it reproducible?

**Comment by oblitum** [comment]
@jeaye Can't dig it further now, it was fine before but now I'm getting these messages showing up over the buffer:

[](http://i.imgur.com/RX7bXZh.png)

I've tried to compile both with Apple Clang, as also with a recent trunk version by using `CC=clang cmake ..`, problem is when I set `CC` in the cmake build style I get:

```
Scanning dependencies of target color_coded_track_api
Tracking API changes...
[  0%] Built target color_coded_track_api
Scanning dependencies of target color_coded_boost
[ 11%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/codecvt_error_category.cpp.o
[ 22%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/operations.cpp.o
[ 33%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/path.cpp.o
[ 44%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/path_traits.cpp.o
[ 55%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/portability.cpp.o
[ 66%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/unique_path.cpp.o
[ 77%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/utf8_codecvt_facet.cpp.o
[ 88%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/system/src/error_code.cpp.o
Linking CXX static library libcolor_coded_boost.a
[ 88%] Built target color_coded_boost
Scanning dependencies of target color_coded
[100%] Building CXX object CMakeFiles/color_coded.dir/src/main.cpp.o
Linking CXX shared library color_coded.so
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      boost::system::system_error::~system_error() in main.cpp.o
      std::__1::bad_function_call::~bad_function_call() in main.cpp.o
      color_coded::clang::compilation_error::~compilation_error() in main.cpp.o
      std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_stringstream() in main.cpp.o
      std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_stringbuf() in main.cpp.o
      std::__1::__function::__func<color_coded::core::queue()::'lambda'(color_coded::async::task const&), std::__1::allocator<color_coded::core::queue()::'lambda'(color_coded::async::task const&)>, color_coded::async::result (color_coded::async::task const&)>::~__func() in main.cpp.o
      std::__1::__function::__base<color_coded::async::result (color_coded::async::task const&)>::~__base() in main.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [color_coded.so] Error 1
make[1]: *** [CMakeFiles/color_coded.dir/all] Error 2
make: *** [all] Error 2
```
This doesn't happen with the normal `./configure --with-cxx=clang++`. Didn't dig this problem either, although it's specific of someone that's using clang's trunk.

I've tried to revert until 50e12090464d6f43dc59006 but this crash is still persisting...

**Comment by jeaye** [comment]
Ah, ok. So the crash is unrelated to cmake. Thanks for clarifying. I'll look deeper into the clang++ compilation, thanks for reporting.

**Comment by oblitum** [comment]
@jeaye I just checked, in this codebase, the libclang crash happens solely when you upgraded to 3.6. 3.5 was fine. Didn't reduce the libclang problem tough.

**Comment by oblitum** [comment]
@jeaye can't send you the code (job stuff).

**Comment by jeaye** [comment]
On Wed, Apr 08, 2015 at 08:56:23AM -0700, Francisco Lopes wrote:
>    [1]@jeaye can't send you the code (job stuff).

Understood. I appreciate the information, either way. I'll make a note of it and hope that I run into it.

**Comment by tony** [comment]
I get an issue, it's searching for clang 3.6.0 for 32 bit linux.

I'm in 64 bit FreeBSD. I have clang 3.6.0 installed.

```
$ uname -a
FreeBSD x200t 11.0-CURRENT FreeBSD 11.0-CURRENT #0: Fri Apr  3 12:15:05 PDT 2015     root@x200t:/usr/obj/usr/src/sys/MYKERNEL  amd64
$ cmake .
-- Looking for Lua 5.2
-- Found Lua
-- Locating trusted Clang/LLVM 3.6.0
CMake Error at cmake/clang/download.cmake:15 (message):
  No pre-built Clang 3.6.0 binaries for 32 bit Linux; this system is not
  supported
Call Stack (most recent call first):
  CMakeLists.txt:34 (include)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/tony/study/vim/color_coded

-- Configuring incomplete, errors occurred!
See also "/home/tony/study/vim/color_coded/CMakeFiles/CMakeOutput.log".

```

**Comment by tony** [comment]
Does it allow me to use my system clang? I already have llvm on my system.

``export LLVM_LIB_PATH=/usr/local/llvm36/lib/`` doesn't make it get detected either.

**Comment by jeaye** [comment]
> Does it allow me to use my system clang? I already have llvm on my system.

No, that's not currently supported. There are plenty enough library issues even using the shipped version of clang. Maybe once things have stabilized, I'll add that feature; I'm not interested in the in-flow of tickets for people using their own system clangs and having things not work.

> I get an issue, it's searching for clang 3.6.0 for 32 bit linux.

Right. FreeBSD detection has just been added today. If you have time, please pull down the latest `cmake` branch and try again. I don't have a FreeBSD machine on which I can test, but I followed the steps that should be required.

**Comment by tony** [comment]
```bash
$ which lua52
/usr/local/bin/lua52

$ ls /usr/local/include/lua52
lauxlib.h lua.h     lua.hpp   luaconf.h lualib.h

$ cmake .
-- Found 64bit system
-- Looking for Lua 5.2
-- Found Lua
-- Locating trusted Clang/LLVM 3.6.0
-- Found clang+llvm-3.6.0-amd64-unknown-freebsd10.tar.xz
-- Clang/LLVM 3.6.0 already extracted
-- Generating sources
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/tony/study/vim/color_coded
   used as include directory in directory /home/tony/study/vim/color_coded
   used as include directory in directory /home/tony/study/vim/color_coded

-- Configuring incomplete, errors occurred!
See also "/home/tony/study/vim/color_coded/CMakeFiles/CMakeOutput.log".

```bash

$ LUA_INCLUDE_DIR=/usr/local/include/lua52 cmake .
```

gives me the same result as above.

**Comment by jeaye** [comment]
@tony That's crazy. Will you confirm, you have the latest changes from the `cmake` branch? What's crazy is that the first couple lines say that Lua5.2 was found. Even crazier, the logic for whether or not Lua is found is based **solely** on whether or not `LUA_INCLUDE_DIR` is set.

You could try adding
```cmake
message(STATUS "Lua dir is: ${LUA_INCLUDE_DIR}")
```
to the bottom of `cmake/lua.cmake` and then running cmake again: `cmake ..` (from the build dir)

**Comment by tony** [comment]
```bash

tony at x in ~/study/vim/color_coded (cmake●●) 
$ cmake .
-- Found 64bit system
-- Looking for Lua 5.2
-- Found Lua
-- Lua dir is: LUA_INCLUDE_DIR-NOTFOUND
-- Locating trusted Clang/LLVM 3.6.0
-- Found clang+llvm-3.6.0-amd64-unknown-freebsd10.tar.xz
-- Clang/LLVM 3.6.0 already extracted
-- Generating sources
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/tony/study/vim/color_coded
   used as include directory in directory /home/tony/study/vim/color_coded
   used as include directory in directory /home/tony/study/vim/color_coded

-- Configuring incomplete, errors occurred!
See also "/home/tony/study/vim/color_coded/CMakeFiles/CMakeOutput.log".

tony at x in ~/study/vim/color_coded (cmake●●) 
$ LUA_INCLUDE_DIR=/usr/local/include/lua52 cmake .  
-- Found 64bit system
-- Looking for Lua 5.2
-- Found Lua
-- Lua dir is: LUA_INCLUDE_DIR-NOTFOUND
-- Locating trusted Clang/LLVM 3.6.0
-- Found clang+llvm-3.6.0-amd64-unknown-freebsd10.tar.xz
-- Clang/LLVM 3.6.0 already extracted
-- Generating sources
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/tony/study/vim/color_coded
   used as include directory in directory /home/tony/study/vim/color_coded
   used as include directory in directory /home/tony/study/vim/color_coded

-- Configuring incomplete, errors occurred!
See also "/home/tony/study/vim/color_coded/CMakeFiles/CMakeOutput.log".
```

**Comment by tony** [comment]
Yes I can confirm this is the latest cmake branch.

**Comment by jeaye** [comment]
Yep, you're running the right code. I also see the issue. On your machine, the variable is set, but it's not set to anything good. I have pushed up some changes which should be helpful. I've also added a couple more logs to help us diagnose what's going on. When you get a chance, please try again.

Thanks for your patience.

**Comment by jeaye** [comment]
I have merged `cmake` into `master` now, since it does seem to be providing more portability. I'll still keep the `cmake` branch for developing fixes for certain platforms.

**Comment by jeaye** [comment]
@tony I've done some more research. Looks like the syntax you're using is incorrect. Instead of:
```bash
FOO=bar make
```
You need to do:
```bash
cmake . -DFOO=bar
```
and then you can use `make` normally.

**Comment by tony** [comment]
@jeaye Thank you.

As of the current clang branch, I am finding Lua succesfully now too, without having to make any additional arguments.

```shell

tony at x in ~/study/vim/color_coded (cmake) 
$ cmake .
-- The C compiler identification is Clang 3.6.0
-- The CXX compiler identification is Clang 3.6.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found 64bit system
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Performing Test COMPILER_SUPPORTS_CXX1Y
-- Performing Test COMPILER_SUPPORTS_CXX1Y - Success
-- Looking for Lua 5.2
-- Looking for Lua 5.1
-- Looking for any Lua
-- Found Lua
--   Lua include /usr/local/include/lua53
--   Lua lib /usr/local/lib/liblua-5.3.so;/usr/lib/libm.so
-- Found Curses: /usr/lib/libcurses.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8") 
-- Locating trusted Clang/LLVM 3.6.0
-- [download 0% complete]
-- [snip]
-- [download 100% complete]
-- Found clang+llvm-3.6.0-amd64-unknown-freebsd10.tar.xz
-- Extracting Clang/LLVM 3.6.0
-- Generating sources
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tony/study/vim/color_coded

```

After that, ``make`` runs and gives an error:

```shell

tony at x in ~/study/vim/color_coded (cmake●) 
$ make
Scanning dependencies of target color_coded_boost
[ 11%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/codecvt_error_category.cpp.o
[ 22%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/operations.cpp.o
[ 33%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/path.cpp.o
[ 44%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/path_traits.cpp.o
[ 55%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/portability.cpp.o
[ 66%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/unique_path.cpp.o
[ 77%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/filesystem/src/utf8_codecvt_facet.cpp.o
[ 88%] Building CXX object CMakeFiles/color_coded_boost.dir/lib/boost/system/src/error_code.cpp.o
Linking CXX static library libcolor_coded_boost.a
[ 88%] Built target color_coded_boost
Scanning dependencies of target color_coded_track_api
make[2]: exec(/home/tony/study/vim/color_coded/lib/track_api) failed (No such file or directory)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/tony/study/vim/color_coded
*** Error code 1

Stop.
make[1]: stopped in /usr/home/tony/study/vim/color_coded
*** Error code 1

Stop.
make: stopped in /usr/home/tony/study/vim/color_coded

tony at x in ~/study/vim/color_coded (cmake●) 
$ ls lib
boost            generate_sources track_api

```

**Comment by tony** [comment]
@jeaye : 

```shell

$ ./lib/track_api 
zsh: ./lib/track_api: bad interpreter: /bin/bash: no such file or directory
```

On my branch in tony/cmake I started to make this /bin/sh / POSIX compliant... In any event, freebsd ports installs bash to ``/usr/local/bin/bash``.

By changing the shebang to ``#!/usr/bin/env bash`` I was able to get it working. FYI systems without bash won't work.

```
tony at x in ~/study/vim/color_coded (cmake●●) 
$ make
[ 88%] Built target color_coded_boost
Tracking API changes ...
[ 88%] Built target color_coded_track_api
Scanning dependencies of target color_coded
[100%] Building CXX object CMakeFiles/color_coded.dir/src/main.cpp.o
Linking CXX shared library color_coded.so
[100%] Built target color_coded

```

**Comment by jeaye** [comment]
Now that's also crazy. Let's approach this systematically.

1) To save you a boatload of trouble, copy your clang+*.tar.gz into the color_coded directory. When you delete your `build` directory for a clean configuration, you can just copy in the tarball again and it won't ever need to re-download.
2) track_api is there! It's a bash script with the shebang of `/bin/bash`. Could this be an issue with your machine? Furthermore, (... you just replied, verifying this ...)

**Comment by jeaye** [comment]
@tony I'll change the shebang to be more portable. I know you've been through hell with color_coded and I really appreciate the help getting things going on your machine.

Now try to open up some code and see if things are working!

**Comment by jeaye** [comment]
The shebang has been updated on `cmake` and `master`.

**Comment by tony** [comment]
It looks like ``make`` completes, but it gives ``color_coded unavailable: you need to compile it (see README.md)``.

```shell

tony at x in ~/.vim/bundle/color_coded (cmake●●) 
$ ls -al
total 50318
drwxr-xr-x   14 tony  tony        28 Apr  9 23:29 .
drwxr-xr-x  105 tony  tony       106 Apr  9 23:23 ..
-rw-r--r--    1 tony  tony        21 Apr  9 23:24 .color_coded
drwxr-xr-x    8 tony  tony        15 Apr  9 23:29 .git
-rw-r--r--    1 tony  tony       166 Apr  9 23:24 .gitignore
-rw-r--r--    1 tony  tony         0 Apr  9 23:24 .gitmodules
-rw-r--r--    1 tony  tony      3009 Apr  9 23:24 .ycm_extra_conf.py
-rw-r--r--    1 tony  tony      3363 Apr  9 23:24 .ycm_extra_conf.pyc
-rw-r--r--    1 tony  tony     27900 Apr  9 23:27 CMakeCache.txt
drwxr-xr-x    7 tony  tony        18 Apr  9 23:29 CMakeFiles
-rw-r--r--    1 tony  tony      1908 Apr  9 23:27 CMakeLists.txt
-rw-r--r--    1 tony  tony      1090 Apr  9 23:24 LICENSE
-rw-r--r--    1 tony  tony     18535 Apr  9 23:27 Makefile
-rw-r--r--    1 tony  tony     10428 Apr  9 23:24 README.md
drwxr-xr-x    3 tony  tony         3 Apr  9 23:24 after
drwxr-xr-x    2 tony  tony         3 Apr  9 23:23 autoload
drwxr-xr-x    7 tony  tony         7 Apr  9 23:24 clang+llvm-3.6.0-amd64-unknown-freebsd10
-rw-r--r--    1 tony  tony  41111272 Apr  9 23:24 clang+llvm-3.6.0-amd64-unknown-freebsd10.tar.xz
drwxr-xr-x    3 tony  tony         7 Apr  9 23:23 cmake
-rw-r--r--    1 tony  tony      2199 Apr  9 23:27 cmake_install.cmake
-rwxr-xr-x    1 tony  tony  19125189 Apr  9 23:29 color_coded.so
drwxr-xr-x    2 tony  tony         3 Apr  9 23:24 colors
drwxr-xr-x    9 tony  tony        11 Apr  9 23:24 include
drwxr-xr-x    3 tony  tony         5 Apr  9 23:24 lib
-rw-r--r--    1 tony  tony    186684 Apr  9 23:29 libcolor_coded_boost.a
drwxr-xr-x    2 tony  tony         3 Apr  9 23:23 plugin
drwxr-xr-x    2 tony  tony         3 Apr  9 23:23 src
drwxr-xr-x    2 tony  tony         4 Apr  9 23:24 test
```

I don't see a ``build`` directory.

Anything you need for me to look for? I have to rebuild vim with ``+profile`` support to get more info.

**Comment by jeaye** [comment]
Ok, the best thing to do here is to jump into the `bin` directory (with `color_coded.so`) and run:
```bash
lua -l color_coded
```
It should drop you into a lua prompt with no errors. If there are errors, please paste them here.

**Comment by jeaye** [comment]
The build directory is optional, but it's generally where you should be building. Instead of in-source builds, which clutter the project directory with build files, it's common to go into a separate build directory and cmake from there. That's why the README suggests
```bash
mkdir build ; cd build
cmake ..
make && make install
```
Note, this doesn't matter; color_coded should work either way.

**Comment by jeaye** [comment]
@tony Also, in case you weren't following the README, make sure that you have said `make install`. :)

**Comment by tony** [comment]
```bash

tony at x in ~/.vim/bundle/color_coded (cmake●●) 
$ lua52 -l color_coded
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> 
```

I'm updating to the latest ``cmake`` branch, clearing things out, and doing it with the build directory.

> Also, in case you weren't following the README, make sure that you have said make install. :)

And that could be it. Checking it out

**Comment by tony** [comment]
![2015-04-09-235655_1276x757_scrot](https://cloud.githubusercontent.com/assets/26336/7083265/48577aac-df14-11e4-90e2-0c131cbd9a59.png)

FreeBSD Current. Looks like we're up and running.

**Comment by jeaye** [comment]
You're the man. Now, you'll need to tweak your colorscheme to use the new highlighting groups, as the README suggests. You can also try out color_coded's builtin colorscheme:
```viml
:color twighlighted
```
If you don't update your colorscheme (or use twighlighted), you won't be taking full advantage of all the different color groups.

**Comment by tony** [comment]
Here is it **without** the plugin:
![2015-04-10-000031_1276x757_scrot](https://cloud.githubusercontent.com/assets/26336/7083291/b28a8540-df14-11e4-97db-b7dd580c0154.png)

I am using ``base16-monokai``. FYI.

I will follow up with twighlighted for both.

**Comment by jeaye** [comment]
Also, since it looks like you're writing C (instead of C++), you should consider adding a `.color_coded` file to your project root which specifies that C should be used. See https://github.com/jeaye/color_coded#using-for-c

**Comment by tony** [comment]
Can their be a vim settings to pass in flags by filetype?  Could you add ``-x c`` by default for c filetype? Can you make it so a user can script it via ``autocmd``?

**Comment by tony** [comment]
@jeaye I tried loading a file in the v8 project and got an error. (https://github.com/v8/v8/blob/master/src/accessors.cc).

I have to recompile vim to give you more info on that. Stand by.

**Comment by tony** [comment]
Having a hold up with compiling vim on BSD. Here is what I have so far:

``[neobundle] Uncaught error while sourcing "color_coded": Vim(execute):E121: Undefined variable: b:current_syntax in function color_coded#enter, line 7``

**Comment by tony** [comment]
This happens when loading a ``.cc`` file.

**Comment by jeaye** [comment]
> Can their be a vim settings to pass in flags by filetype?

That's not currently possible, but it's something that's very reasonable. The only issue I foresee is trying to decide whether or not the flags in `.color_coded` end up being applied to all file types, or just some. This might require the `.color_coded` file to be more complex, having groupings or flags based on file types. I can make an issue about this as a task. For now, you need to set it project-wide.

**Comment by jeaye** [comment]
@tony `b:current_syntax` is an internal vim variable. The docs are here: http://vimdoc.sourceforge.net/htmldoc/syntax.html (can't link you directly, but searching for `b:current_syntax` shows the first result properly on the page)

**Comment by tony** [comment]
@jeaye : Looking into it.

Here is the profile.log and vim version here from the error: https://gist.github.com/tony/a23eb36f188102120df6

It's not convenient to have to put a ``.color_coded`` in every C project. In my case it'd be ``/usr/src`` in freebsd and various open source projects I study in ``~/study/c``.  YCM has a project config for the users ``$HOME`` directory as a fallback if there isn't a config in the project.

**Comment by jeaye** [comment]
> It's not convenient to have to put a .color_coded in every C project.

You don't need to do that. You should really read the README. :P color_coded will search up to / from the current directory and use whichever `.color_coded` it finds first.

**Comment by jeaye** [comment]
I'm closing this issue, since `cmake` has been merged into `master`. @tony Feel free to still comment here on your `b:current_syntax` issue.

**Comment by tony** [comment]
@jeaye Let's make it into it's own issue.

**Comment by oblitum** [comment]
@jeaye I've figured out my cmake build problem [at a previous comment](https://github.com/jeaye/color_coded/issues/25#issuecomment-90937031) is because of this:

https://llvm.org/bugs/show_bug.cgi?id=22951

**Comment by jeaye** [comment]
On Mon, Apr 13, 2015 at 07:28:25PM -0700, Francisco Lopes wrote:
>    [1]@jeaye I've figured out my cmake build problem [2]at a previous comment
>    is because of this:
> 
>    [3]https://llvm.org/bugs/show_bug.cgi?id=22951

Hm, this doesn't say that `-std=c++1y` has the same issue. Does it?

**Comment by oblitum** [comment]
yeah it doesn't specify that. I'm still checking whether it got fixed at the libc++ repo, or the clang one. Because AFAIK, I don't have a custom libc++ on OS X, so this should be reproducing with the system one that may have got updated or something. Still checking why I get this...

**Comment by oblitum** [comment]
It's in my current clang trunk revision... it's fixed in clang.

**Comment by jeaye** [comment]
On Mon, Apr 13, 2015 at 07:47:33PM -0700, Francisco Lopes wrote:
>    It's in my current clang trunk revision... it's fixed in clang.

Hehe. So this isn't an issue anyone else is likely to have then.

**Comment by oblitum** [comment]
yep.
