### ISSUE TITLE
Do not use C++14 library features

### ISSUE THREAD

**Issue by HappyCerberus** [jeaye/color_coded#27]
I'm all for modern C++, but you are using C++14 library features. This is problematic as replacing a core system library is not as easy as replacing a compiler.

In particular the `decay_t` is not present in libstdc++4.8

**Comment by HappyCerberus** [comment]
And this actually seems to be all that is missing (apart from a small `gets` related bug in libc). Adding this code fragment to the `util.hpp` seems to fix the issue.

    namespace std
    {
	    template< class T >
	    using decay_t = typename decay<T>::type;
    }

**Comment by jeaye** [comment]
So, carrying over from the previous ticket, you're saying that your compiler supports C++1y/14 but your stdlib doesn't? I'm curious what kind of setup you have where this is the case. Which OS/distro and compiler?

**Comment by jeaye** [comment]
> Adding this code fragment to the util.hpp seems to fix the issue.

Unfortunately, we can't just do this. :P It'd break for anyone that already has `decay_t`. Right now, I'm trying to see why you don't have a C++14 stdlib, but you have a C++14 compiler.

**Comment by HappyCerberus** [comment]
Current OpenSuSe. You can easily install modern clang, and newer GCC, both of which will support C++14 language features, but you can't change the stdlib as everything is compiled against it.

**Comment by jeaye** [comment]
Thanks for letting me know. Let's keep going on this ticket instead of #25, since this is more focused and your issue is not related to CMake.

**Comment by HappyCerberus** [comment]
As for the GCC issue, this version of OpenSuSe as GCC 4.8 by default. I will try to test with GCC 4.9.

**Comment by jeaye** [comment]
> Current OpenSuSe. You can easily install modern clang, and newer GCC, both of which will support C++14 language features, but you can't change the stdlib as everything is compiled against it.

I haven't tested color_coded on OpenSuSe, clearly, but I don't currently see why you couldn't use the C++14 stdlib to compile color_coded. It compiles its own boost, it ships with its own clang, and the only other libraries to which it links (other than the stdlib) are C system-level libraries. Have you tried this and found you ran into link-time or run-time issues?

Furthermore, since you're the first one running color_coded on OpenSuSe, once we get your compilation issues resolved, will you outline any manual steps you were required to take so I can add them to the README?

> As for the GCC issue, this version of OpenSuSe as GCC 4.8 by default. I will try to test with GCC 4.9.

Thank you very much. Once things are working, I'd love to get your input on the required steps.

**Comment by oblitum** [comment]
@HappyCerberus just a suggestion: Have you tried to use libc++? I've used it coupled with libc++abi on two Linux distributions as an option without problems. If your platform is not offering any option for an up to date libstdc++ lib, this may be a way out.

**Comment by oblitum** [comment]
@HappyCerberus for compiling with clang I mean.

**Comment by rdnetto** [comment]
I believe I am affected by this issue as well. Distro is Sabayon/Gentoo, (default) C++ compiler is GCC 4.8. Using Clang 3.5 as the compiler produces the error "'cstddef' file not found". Will post back with more info once I've emerged GCC 4.9.

**Comment by jeaye** [comment]
This doesn't seem to be progressing. I'd like to continue using C++14 and it seems to be well enough supported on all target platforms. If you run into specific issues, let me know.
