### ISSUE TITLE
FreeBSD documentation

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#34]
Add documentation to README for freebsd installation.

**Comment by jeaye** [comment]
Are you able to outline the steps you had to take in order to get things working? I know that cmake ended up working without manual intervention in the end, but I believe you had to install GCC 4.9. Correct?

**Comment by tony** [comment]
@jeaye You can assign this and #35 to me as documentation.

I'm going to get a jail setup and do the process once more and double check it before a PR.

**Comment by jeaye** [comment]
I can't assign assign these to you unless you're a marked as a contributor. I'll leave me assigned for now, but you're the man on these. Many thanks.

**Comment by tony** [comment]
You're doing fine. Will get this done asap, need to QA in a fresh environment.

**Comment by jeaye** [comment]
Closing now, after your PR.
