### ISSUE TITLE
Add NeoBundle directive to README

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#35]
* Add NeoBundle directive to pull and build via cmake.
* Test on FreeBSD, Debian

**Comment by tony** [comment]
@jeaye I think it's better to put this under documentation as a label.

**Comment by jeaye** [comment]
Agreed.

**Comment by tony** [comment]
Here is what I have, @jeaye : Are you using NeoBundle?

```viml
NeoBundleLazy 'jeaye/color_coded', { 
      \ 'build': {
      \   'unix': 'cmake . && make && make install',
      \ },
      \ 'autoload' : { 'filetypes' : ['c', 'cpp', 'objc'] }
  \}
```

**Comment by tony** [comment]
I can confirm the above works on FreeBSD and Debian jessie.

This also assures the plugin is only sourced into vim upon loading a c, c++ or objective c file.

**Comment by oblitum** [comment]
@tony what about obj-c++. I know it exists but I never touch such thing so, not sure its filetype differs from obj-c, I don't recall.

**Comment by tony** [comment]
@oblitum You know know what ``filetype`` vim would detect it as,``obj-c++``?

**Comment by oblitum** [comment]
@tony I think it's objcpp.

**Comment by jeaye** [comment]
It's `m` and `mm`.

**Comment by jeaye** [comment]
@tony The readme outlines color_coded's filetype support:
```viml
let g:color_coded_filetypes = ['c', 'h', 'cpp', 'hpp', 'cc', 'm', 'mm']
```
That is, color_coded is already checking the filetype to see if it needs to work.

**Comment by jeaye** [comment]
> Are you using NeoBundle?

Nope, I use Vundle. If needed, I can set NeoBundle up in an untested platform.

**Comment by jeaye** [comment]
Verified, the filetype for Obj-C is `objc`. I'll also update that config variable.

**Comment by oblitum** [comment]
@jeaye my comment was intended for the `objcpp` vim filetype.

**Comment by jeaye** [comment]
@oblitum Yeah, I was all over the place. Had just woken up. >.< Anyway, `objc` and `objcpp` are valid vim filetypes.
