### ISSUE TITLE
random selection

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#48]
color-coded sporadically creates a kind persistent word selection. I mean, some text with selection background that I'm unable turn off.

**Comment by oblitum** [comment]
I've checked this happens with the words that are at the beginning of the line.

**Comment by jeaye** [comment]
I think there's an issue with buffer changing when not using tabs and I think it might be described in a similar way to what you've issued. It's something I'm looking into, but this might help your reproduction steps.

**Comment by jeaye** [comment]
I've merged these changes with master now and a number of "random highlighting" issues have been resolved. So far, I haven't been able to reproduce any such cases with the new logic.
