### ISSUE TITLE
vim segfault on quit

### ISSUE THREAD

**Issue by UnrealQuester** [jeaye/color_coded#50]
When trying to quit vim directly after opening a c++ file, it segfaults. This only happens about 50% of the time and I only noticed it today despite using this plugin for serveral days now.

Attaching a debugger shows that the segfault happens in `std::condition_variable::wait`. The only place where we wait for something is in `async/queue.hpp`. A possible explanation of why this is happening:
* The queue object gets destroyed
* It calls `thread::detach` in the destructor
* The condition variable inside `work()` wakes up and checks `has_work_`
* As the object was already destroyed, the member variable does not exist anymore and causes a segfault

**Comment by jeaye** [comment]
This may be related to a crash I've been seeing and I was also considering this queue issue. I'll put up a patch soon.

**Comment by jeaye** [comment]
@UnrealQuester That wasn't the only issue, it seems. By the time the queue was destructed, clang might've already been torn down; if the queue was still processing a task, this would also cause a crash. The solution is to listen for `VimLeave` and cleanup the worker thread while everything is still vaild.

Let me know how this works for you; it looks like everything is good on my end.

**Comment by UnrealQuester** [comment]
Can confirm that the bug appears to be fixed.
