### ISSUE TITLE
Resolving "color_coded unavailable: requires lua" error

### ISSUE THREAD

**Issue by floyd-m-chitalu** [jeaye/color_coded#52]
Hi,

After following all instructions as contained in the project's readme, I have been unable to correctly integrate this plugin into vim. Upon invoking the vim command within the terminal,  I recieve the following ouput just before vim begins execution:
________________________
floyd@love-xpress:~$ vim
color_coded unavailable: requires lua
Press ENTER or type command to continue
________________________

I can confirm that lua has also been installed on my laptop with the following output:
________________________
floyd@love-xpress:~$ lua -v
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
________________________
... and that a correct version of vim too has been installed:
________________________
floyd@love-xpress:~$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  7 2015 14:22:51)
Included patches: 1-728
Compiled by floyd@love-xpress
Huge version with GTK2 GUI.  Features included (+) or not (-):
...
________________________

Where have I gone wrong?

Thanks

- Floyd

**Comment by jeaye** [comment]
You've left out the key part! It's not just about whether or not you have lua installed, it's also about whether or not vim is compiled with +lua. That's shown in the `vim --version`.

**Comment by floyd-m-chitalu** [comment]
Thanks! I believe that was my problem. 

Unfortunately however, the process of compiling vim with lua is proving to be too hectic to be worth the time so I'm leaving the task for another day. I have spent too much time on it with no progress.

For others that may face a similar issue in the future, the following sites have been slightly useful:
https://coderwall.com/p/cef4wq/compile-vim-with-luajit
https://github.com/Shougo/neocomplete.vim/issues/31

**Comment by jeaye** [comment]
@floyd-m-chitalu As the README says, **do not use luajit**. luajit does not work in native shared objects such as color_coded, due to its linking dependencies.

What platform are you on? If it's OS X, use homebrew. If it's a Linux distro, are you sure vim with +lua isn't in the package repositories?

**Comment by floyd-m-chitalu** [comment]
@jeaye went back to it see if I could resolve the issue and I can confirm that I have been able to fix it. I was not installing vim correctly. The features list shown after calling vim with the "--version" command now displays "+lua" instead of "-lua" like it did before.

Thank you. 

And I am using Ubuntu 14.04 LTS

**Comment by jeaye** [comment]
On Fri, May 08, 2015 at 06:51:44AM -0700, Floyd Chitalu wrote:
>    [1]@jeaye went back to it see if I could resolve the issue and I can
>    confirm that I have been able to fix it. I was not installing vim
>    correctly. The features list shown after calling vim with the "--version"
>    command now displays "+lua" instead of "-lua" like it did before.

Glad to hear things are working! Enjoy.

**Comment by JuanCabre** [comment]
Hello,

I got the same error. I am using Arch Linux, and I have vim compiled with lua. However, yesterday, the lua package was updated (from pacman's log: `upgraded lua (5.3.3-2 -> 5.3.4-1)`). Now, when I open vim, I get the error `color_coded unavailable: requires lua`

**Comment by jeaye** [comment]
Yep, Arch broke something again; I've just started seeing this on my Arch machine as well. I don't have the time to look into it now, but perhaps tomorrow. In the meantime, if you feel like investigating, feel free and let me know what you find.

Thanks for the report.

**Comment by pierremoreau** [comment]
I have the same issue as well on Arch. I tried to test the Lua command, by entering `:lua foo`, and got an error message that it could not load `liblua.so.5.3.3`: I am running on testing, which updated to 5.3.4. Downgrading back to lua-5.3.3 solved the issue and I no longer get the warning from color_coded.

**Comment by thfr** [comment]
It simply means, that vim has not been compiled yet again the new lua version. You can do it yourself:
`yaourt -G vim; cd vim; makepkg; yaourt -U <vim/gvim package>`

**Comment by jeaye** [comment]
Right you are! The official vim packages should work fine, but anything from AUR will need a rebuild.

**Comment by ArjunSahlot** [comment]
Hi,

I still get the same error. It is probably because `vim --version` outputs `-lua` instead of `+lua`. I have `lua5.3.3` installed, how do I fix vim to make it `+lua`?
