### ISSUE TITLE
Very slow to type when editing an slightly large file

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#6]
Tried it with SemaCodeComplete.cpp from clang codebase.

**Comment by jeaye** [comment]
Yeah, this file, on my machine, is over 7,200 lines long. That said, this *shouldn't* be an issue. I believe this is due to string building in lua when handing to C++. Each key press builds a 7.2K line string synchronously before handing it off to the native backend.

I certainly consider this an issue and will add this to the 0.1 milestone. Thanks for reporting.

**Comment by jeaye** [comment]
@oblitum You should notice big improvments in larger files. Let me know if this is still an issue.

**Comment by oblitum** [comment]
@jeaye thanks! I'll try it further as soon as I can.

**Comment by oblitum** [comment]
@jeaye off-topic: by the way, have you tried my ycm fork these days? It has got some nice experimental stuff.

**Comment by jeaye** [comment]
I hadn't seen it. Just took a look at the gif and it looks slick; I'll give it a shot!

**Comment by jeaye** [comment]
@oblitum In the gif, the second parameter has the type `U` and the third has the type `int`. Bug?

**Comment by oblitum** [comment]
@jeaye yeah, not a bug: type resolution while typing :-)

**Comment by oblitum** [comment]
@jeaye didn't see that level not even in Visual Studio.

**Comment by jeaye** [comment]
On Mon, Mar 23, 2015 at 10:04:45PM -0700, Francisco Lopes wrote:
>    [1]@jeaye didn't see that level not even in Visual Studio.

Aye, that's slick. Now we just need to integrate it with color_coded so
there's no more duplication compilation. ;)

**Comment by oblitum** [comment]
Ah, indeed.

**Comment by oblitum** [comment]
Great work! It's coupling quite nicely with my current colorscheme, seoul256. It seems to have got in a state I may try it in a daily basis.

**Comment by jeaye** [comment]
Glad to hear!
