### ISSUE TITLE
Highlighting of keywords is too coarse

### ISSUE THREAD

**Issue by waedt** [jeaye/color_coded#62]
Currently color_coded applies the "Keyword" highlight very coarsely, with no distinction between different types of keywords. This is a problem for me because I would like to have void, int, and other builtin type names highlighted as types instead of keywords for consistency.  Being that the set of keywords is reasonably small and doesn't change often, perhaps an option could be added to skip highlighting keywords altogether and just let vim's syntax files handle them?

**Comment by jeaye** [comment]
This is something worth investigating, however, I want to point out that we can't just allow vim to handle the keyword highlighting. Vim's pretty lazy about how it highlights. Comments, right now, are all handled by vim and that causes a number of issues where comments, when scrolling, can become highlighted as thought the previously scrolled text is superimposed. The only way I've found to fix this is to hand the highlighting back over to color_coded.

That said, distinguishing between keywords and intrinsic types would be nice. I'll leave this open until that's worked out.

**Comment by jeaye** [comment]
@waedt I've disabled keyword highlighting in color_coded, for now; it's up to vim to handle it. Let me know how it goes for you.
