### ISSUE TITLE
relative include path error, real include path correct.

### ISSUE THREAD

**Issue by myme5261314** [jeaye/color_coded#63]
I have a C++ project which has Makefile/include dir/src dir under the project root directory.
I use Ycm-Generator to generate both .ycm_extra_conf.py and .color_coded, the generating process both runs without errors. And its output is something like
Color_coded works incorrect. The error seems like this "MySelfDefine.hpp not found."
> .color_coded
-x
c++
-DNDEBUG
-I/usr/include/openni2
-I/usr/local/cuda/include
-I/usr/local/include
**-Iinclude** or **-I./include** both error, **-I/home/user/project_path/include** works correctly.
-Wall
-Werror

YCM works fine.
> .ycm_extra_conf.py
flags = [
    '-x',
    'c++',
    '-DNDEBUG',
    '-I/usr/include/openni2',
    '-I/usr/local/cuda/include',
    '-I/usr/local/include',
    **'-Iinclude',**
    '-Wall',
    '-Werror',
]

**Comment by jeaye** [comment]
@myme5261314 color_coded uses these paths relative to vim's working directory when you open it. Thus, you should open vim at the root level of your project, adjacent to your `.color_coded` file. If you try to open below that directory, say, in `src`, you will run into inclusion issues like this.

First, verify with me that you're opening vim as described. Hopefully that's just the issue and it's simple to clear up.

**Comment by myme5261314** [comment]
@jeaye I've checked that
1.  I opened gvim from the terminal whose working directory is the project root directory.
2.  in vim :e src/main.cpp.
3. in vim :CCerror
4. the error message is 'MyXXXX.hpp' file not found. BTW, relative path **-Iinclude** used in .color_coded file.

So I wonder is it possible to accomplish the feature I was demanding?
It's not weird to place Makefile under root level ./ while the header file in ./include and implementation file in ./src, could color_coded have the ability to handle this kind of scene?

**Comment by jeaye** [comment]
On Tue, Sep 22, 2015 at 01:35:15AM -0700, Peng Liu wrote:
>    [1]@jeaye I've checked that
>    1. I opened gvim from the terminal whose working directory is the project
>    root directory.
>    2. in vim :e src/main.cpp.
>    3. in vim :CCerror
>    4. the error message is 'MyXXXX.hpp' file not found. BTW, relative path
>    -Iinclude used in .color_coded file.
> 
>    So I wonder is it possible to accomplish the feature I was demanding?
>    It's not weird to place Makefile under root level ./ while the header file
>    in ./include and implementation file in ./src, could color_coded have the
>    ability to handle this kind of scene?

Every project I have uses `./include` and `./src` and a root-level (or out-of-source) Makefile with no complaints from color_coded. Would you be willing to make a small example project, on Github, and link it here so I can try it locally? Relative include paths _are_ already a feature in color_coded and they've been there for quite some time. So there must be something fishy with your setup, I think.

Let me know if you have the time to make that small example repo and I'll see if I can reproduce the issue.

**Comment by myme5261314** [comment]
I've created a toy project from my current issuing project, and I've confirmed the head file not found error still exists.

You need to clone it and use vim to edit the **src/main.cpp** and then type **:CCerror** in vim, see what you've got. I've got 
> /tmp/color_coded/main.cpp:8:10: fatal error: 'main.h' file not found

> [Toy Project](https://github.com/myme5261314/toy-issue63-color_coded.git)

**Comment by jeaye** [comment]
On Wed, Sep 23, 2015 at 02:19:52AM -0700, Peng Liu wrote:
>    I've created a toy project from my current issuing project, and I've
>    confirmed the head file not found error still exists.
> 
>    You need to clone it and use vim to edit the src/main.cpp and then type
>    :CCerror in vim, see what you've got. I've got
> 
>      /tmp/color_coded/main.cpp:8:10: fatal error: 'main.h' file not found
> 
>      [1]Toy Project

I don't see a .color_coded file in that repo. Are you sure you added one?

**Comment by myme5261314** [comment]
You could generate it by YCM-Generator, The makefile is setting ok, so you could just generate it or use my current generated one.
> .color_coded
>-x
c++
-DDEBUG
-I/usr/local/include
-Iinclude
-Wall
-Werror
-std=c++11

**Comment by jeaye** [comment]
On Wed, Sep 23, 2015 at 02:37:29AM -0700, Peng Liu wrote:
>    You could generate it by YCM-Generator, The makefile is setting ok, so you
>    could just generate it or use my current generated one.
> 
>      .color_coded
>      -x
>      c++
>      -DDEBUG
>      -I/usr/local/include
>      -Iinclude
>      -Wall
>      -Werror
>      -std=c++11

Copy/pasting that into a .color_coded file in the root of the repo, opening src/main.cpp, and running :CCerror shows that there are no errors. *Please* copy in a complete and stand-alone test case, including the exact .color_coded file you're using. Typically the .color_coded file should just be added into the repo anyway.

**Comment by myme5261314** [comment]
I've add the .color_coded file to the repo. Please pull it again. The error exists and it's shown in the video.
> [example video](http://showterm.io/ed34de8769d6c782c263d)

**Comment by jeaye** [comment]
On Wed, Sep 23, 2015 at 03:05:56AM -0700, Peng Liu wrote:
>    I've add the .color_coded file to the repo. Please pull it again. The
>    error exists and it's shown in the video.
> 
>      [1]example video
> 

In the video, you didn't move the cursor _at all_, meaning color_coded didn't get a chance to update. Vim doesn't have an async/timer API; color_coded can only be polled when you actually do something. Will you please try again and allow color_coded the proper events it need to propagate changes? You should see some highlighting change when it's taken effect.

**Comment by myme5261314** [comment]
@jeaye I actually haven't moved the cursor in the video. But I think that's not the key point.
1. I mean, I launch the vim from project root directory. The **:pwd** returns the project path. Then **:CCerror** shows no error.
2. Then **:e src/main.cpp**, **:pwd** returns the path of src. And then even though I move the cursor around or **:w** to save the file. Anyway, **:CCerror** shows something like that:
>  /tmp/color_coded/main.cpp:8:10: fatal error: 'main.h' file not found

**Comment by jeaye** [comment]
On Wed, Sep 23, 2015 at 03:50:06AM -0700, Peng Liu wrote:
>    [1]@jeaye I actually haven't moved the cursor in the video. But I think
>    that's not the key point.
>    1. I mean, I launch the vim from project root directory. The :pwd returns
>    the project path. Then :CCerror shows no error.
>    2. Then :e src/main.cpp, :pwd returns the path of src. And then even
>    though I move the cursor around or :w to save the file. Anyway, :CCerror
>    shows something like that:
> 
>      /tmp/color_coded/main.cpp:8:10: fatal error: 'main.h' file not found
> 

I'm sorry, Peng, but I can't reproduce this on Linux x86_64 (Slackware) or OS X. Please answer the following.

1. What OS/version are you using with what vim version?
2. Does opening color_coded's src/main.cpp, from its root dir, give you the same issue?

Thanks.

**Comment by myme5261314** [comment]
1. My OS version and vim version is below:

> **OS**: 3.16.0-46-generic~**14.04.1-Ubuntu** SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 GNU/Linux
> **Vim**: Compiled from official github source.
x86_64 GNU/LinuxVIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 18 2015 11:25:16)
including patches: 1-873
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm

2. yes, it would give me the same issue if I type **vim src/main.cpp** on the terminal whose working directory is the project root path.
Here's the tree structure of the project generated by the command **tree -a -I .git**

>.
├── Bin
│   ├── Intermediate
│   │   └── x64-DEBUG
│   │       └── toy
│   │           ├── main.d
│   │           └── main.o
│   └── x64-DEBUG
│       └── toy
├── .color_coded
├── CommonCppMakefile
├── CommonDefs.mak
├── CommonTargets.mak
├── .cproject
├── .gitignore
├── include
│   └── main.h
├── Makefile
├── Platform.Arm
├── Platform.x64
├── Platform.x86
├── .project
├── README.md
├── .settings
│   ├── language.settings.xml
│   └── org.eclipse.cdt.codan.core.prefs
├── src
│   └── main.cpp
├── .ycm_extra_conf.py
└── .ycm_extra_conf.pyc
8 directories, 21 files

3. If you would like to check my **.vimrc** file, it's on my [repo](https://github.com/myme5261314/myvimrc), note that file **.vimrc** is the one I'm using under Ubuntu.

**Comment by jeaye** [comment]
I've pushed up some changes which improve how color_coded handles relative files (along with various other fixes). Perhaps this will resolve your issue; unfortunately, I haven't been able to reproduce it at all.
