### ISSUE TITLE
Plugin does not work with ncurses 6.0

### ISSUE THREAD

**Issue by ChakAndree** [jeaye/color_coded#64]
Hi! After the upgrade my distro plugin has stopped working. I use Arch Linux. I found out that plugin does not work with ncurses 6.0 ( libncursesw.so.6 ). I downloaded ncurses 5.9 from Ubuntu repository and run vim (fish shell): env LD_LIBRARY_PATH=&lt;path to ncurses 5.9 lib&gt; vim main.cpp. It works! A similar problem with plugin clang_complete. Plugin vim-clang works with ncurses 6.0.

**Comment by jeaye** [comment]
I'm running Arch with ncurses 6.0-3 and I haven't seen any issues. Let me know if this is still a problem for you.

**Comment by ChakAndree** [comment]
Helped disabling the plugin clang_complete. You used the plugin clang_complete with ncurses 6.0? Enabled plugin is disabled syntax highlighting, command line is missing, words are placed randomly, etc.

**Comment by jeaye** [comment]
>    Helped disabling the plugin clang_complete. You used the plugin
>    clang_complete with ncurses 6.0? Enabled plugin is disabled syntax
>    highlighting, command line is missing, words are placed randomly, etc.

No, I don't use clang_complete (I use YouCompleteMe) and this isn't the place to report issues with it. Are you having issues with color_coded?

**Comment by ChakAndree** [comment]
There are no questions. Thanks for the reply.
