### ISSUE TITLE
Conflict with other highlighting plugins

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#8]
I use [vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace) which is a quite useful plugin for me, but enabling color_coded seems to turn it unusable.

**Comment by jeaye** [comment]
Can you provide any more information on what becomes unusable? I'm aware that color_coded doesn't play very nicely with other highlighting plugins; it's difficult to, since there's no standard and no scalable way of playing well with specific behavior. Depending on what's wrong, we might be able to turn off that functionality (it may not be needed) in color_coded, or put it behind an option.

**Comment by oblitum** [comment]
My wish is to still be able to spot whitespaces. In my current setup my colorscheme is seoul256, with color_coded and vim-better-whitespace. With color_coded enable whitespace highlighting at the end of lines doesn't display. If I move to the end of some line with ending whitespace and press `a` for example to enter insert-mode, the whitespace highlighting blinks.

**Comment by jeaye** [comment]
On Tue, Mar 24, 2015 at 09:58:56PM -0700, Francisco Lopes wrote:
>    My wish is to still be able to spot whitespaces. In my current setup my
>    colorscheme is seoul256, with color_coded and vim-better-whitespace. With
>    color_coded enable whitespace highlighting at the end of lines doesn't
>    display. If I move to the end of some line with ending whitespace and
>    press a for example to enter insert-mode, the whitespace highlighting
>    blinks.

Word. I think I have an idea as to what's happening; if I'm correct, it could be an easy fix. I'll install this plugin and see if I can replicate your issues, then let you know how my idea goes.

As always, thanks for reporting the issue and filling in the details.

**Comment by jeaye** [comment]
Update: My suspicion was correct. I have the whitespace showing up properly now. I need to do some more testing to ensure that there are no side effects with this change.

**Comment by jeaye** [comment]
Everything appears to be working properly. I've updated master; will you let me know how it goes for you?

**Comment by oblitum** [comment]
It seems to have affected #6. Getting hard hangs.

**Comment by jeaye** [comment]
I'm not experiencing any such slowdown; it's still much faster than it was before #6 was fixed. What are these "hard hangs"?

**Comment by oblitum** [comment]
I was suspecting it could be related to vim itself dealing with the colorscheme support, but I'm not sure. For me it's much worst than #6, I'm almost unable to move the cursor after the colorscheme loads. Vim blocks processing, it's hard to exit if I happen to ask it to move too much.   
I've just confirmed it's in this last commit for me by reverting it.

**Comment by oblitum** [comment]
I'll get back later, see ya.

**Comment by jeaye** [comment]
On Wed, Mar 25, 2015 at 04:49:57AM -0700, Francisco Lopes wrote:
>    I was suspecting it could be related to vim itself dealing with the
>    colorscheme support, but I'm not sure. For me it's much worst than [1]#6,
>    I'm almost unable to move the cursor after the colorscheme loads. Vim
>    blocks processing, it's hard to exit if I happen to ask it to move too
>    much.

That's crazy. Will you try the latest master without all of your other plugins and tell me if it's still slow? My guess is that we're now interfering with a different plugin you're using.

**Comment by oblitum** [comment]
I've just tried it without any other plugin, it has got the same behavior regardless. It has nothing to do with incompatibility with other plugins. Are you on OS X?

**Comment by oblitum** [comment]
Ah, I changed back the title since this started about conflicts.

**Comment by jeaye** [comment]
On Wed, Mar 25, 2015 at 08:04:10PM -0700, Francisco Lopes wrote:
>    I've just tried it without any other plugin, it has got the same behavior
>    regardless. It has nothing to do with incompatibility with other plugins.
>    Are you on OS X?

Nope. I know what's going on though. You're scrolling through the file and I was just jumping to the bottom. Looks like I need a more clever solution. The "fix" for #8 was to not clear all matches (highlighting) before applying the new ones; the issue with this is that vim's highlighting simply can't handle thousands of lines of very highlighted code. What I'll need to do is perhaps selectively clear everything that's outside the visible window.

The current behavior, aside from the clearmatches call, only highlights what's visible + a few extra lines on either side. This keeps vim fast in any size file. The summarized issue is that, since we're not clearing, the amount of highlighted code grows as you scroll. I'll look into a good solution.

**Comment by oblitum** [comment]
@jeaye just a bit of more info, the slowness doesn't show up right away. It shows up only after I move the cursor for a while, some seconds, and then it gets slower cumulatively.

I've worked with highlighting before, not sure whether you checked or is already using a feature of partial application of highlighting, if I recall correctly Vim does has something about line range of updates or something.

**Comment by jeaye** [comment]
On Wed, Mar 25, 2015 at 08:37:34PM -0700, Francisco Lopes wrote:
>    [1]@jeaye just a bit of more info, the slowness doesn't show up right
>    away. It shows up only after I move the cursor for a while, some seconds,
>    and then it gets slower cumulatively.

Yup, these symptoms fit my diagnosis perfectly. Thanks.

>    I've worked with highlighting before, not sure whether you checked or is
>    already using a feature of partial application of highlighting, if I
>    recall correctly Vim does has something about line range of updates or
>    something.

That's likely. I'll do some more research later today to see what I can find.

**Comment by oblitum** [comment]
> That's likely. I'll do some more research later today to see what I can find.
Ok, don't trust me, my memory may be confusing it with range for syntax matching. I just don't recall it clearly but there's some line range support on something.

**Comment by jeaye** [comment]
Unfortunately, vim doesn't seem to provide a way to clear matches within line ranges. This means that we can either clear individual matches (using an ID obtained while creating the match) or we can just delete them all. There may be a way to obtain all IDs in a given line range so that we can clear them all individually. For now, I've reverted the commit; the performance should be back and the whitespace plugin should no longer be compatible. I'll let you know what I find.

**Comment by oblitum** [comment]
OK, thanks for the effort.

**Comment by jeaye** [comment]
On Fri, Mar 27, 2015 at 06:12:52AM -0700, Francisco Lopes wrote:
>    OK, thanks for the effort.

Actually, great news. I'm working on a solution which should be faster than the original code and it works in an unintrusive manner (aside from that which color_coded actually highlights) alongside other highlighting plugins. I'm hoping to have it pushed soon.

**Comment by oblitum** [comment]
Well, many thanks so! :-)

**Comment by oblitum** [comment]
I'm eager to be able to start adopting it. I'd like to try making a colorscheme for my tastes based on it.

**Comment by oblitum** [comment]
OT: Is it supporting brace highlighting? I know clang can tell you whether something is a brace. It would be nice if it had brace and operator highlighting integrated. Operators could be done in a non-clang way, like Valloric's vim-operator-highlight plugin, but braces needs special semantic atention to get right, template braces for example, impossible to get right with vim resources solely, my own experience from a rainbow braces plugin.

**Comment by jeaye** [comment]
On Fri, Mar 27, 2015 at 06:22:23AM -0700, Francisco Lopes wrote:
>    OT: Is it supporting brace highlighting? I know clang can tell you whether
>    something is a brace. It would be nice if it had brace and operator
>    highlighting integrated. Operators could be done in a non-clang way, like
>    Valloric's vim-operator-highlight plugin, but braces needs special
>    semantic atention to get right, template braces for example, impossible to
>    get right with vim resources solely, my own experience from a rainbow
>    braces plugin.

Braces are highlighted as punctuation. I use rainbow parens for my brace highlighting. I'd consider adding more functionality for this, but only after 1.0.

**Comment by oblitum** [comment]
Nice, I stopped caring about rainbows, if I could get all braces highlighted in a uniform way, with operators in another uniform way, I would be much happy.

**Comment by jeaye** [comment]
Want to checkout the `matches` branch and try it out? :D

**Comment by oblitum** [comment]
sure, doing it now.

**Comment by oblitum** [comment]
notice, after make/configure it's all leaving an untracked `include/env/impl.hpp` in the repo.

**Comment by jeaye** [comment]
Yeah, I've been meaning to add that to the .gitignore. Will do so now.

**Comment by oblitum** [comment]
Just tried, looks perfect, fixed as intended.

**Comment by jeaye** [comment]
\o/ Thanks!

**Comment by jeaye** [comment]
I'd love to see that color scheme, if you decide to make it.

**Comment by oblitum** [comment]
It'll be my next endeavor in my freetime.

**Comment by oblitum** [comment]
Not sure whether this is a problem with the colorscheme, my configuration highlights the background of a line with a warning, but with color_coded enabled it gets cut in pieces:

http://bl.ocks.org/anonymous/raw/03f5b4d485258e14b724/

**Comment by jeaye** [comment]
On Sun, Mar 29, 2015 at 01:50:30PM -0700, Francisco Lopes wrote:
>    Not sure whether this is a problem with the colorscheme, my configuration
>    highlights the background of a line with a warning, but with color_coded
>    enabled it gets cut in pieces:
> 
>    [1]http://bl.ocks.org/anonymous/raw/03f5b4d485258e14b724/

Will you please paste your colorscheme? color_coded doesn't actually do any color highlighting; it just maps characters to groups. If your colorscheme has the `bg` property set to a certain color, it's going to force that color. I'd check to make sure you don't have it set for each of your clang groups and see if that helps. If not, please link me to the colorscheme contents.
