### ISSUE TITLE
NeoBundle installation isn't working

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#86]
https://github.com/jeaye/color_coded#neobundle

```viml
NeoBundleLazy 'jeaye/color_coded', {
  \ 'build': {
    \   'unix': 'cmake . && make && make install',
  \ },
  \ 'autoload': { 'filetypes' : ['c', 'cpp', 'objc', 'objcpp'] },
  \ 'build_commands' : ['cmake', 'make']
\}
```

This is a tricky one.  The way we have it now can end up contaminating the bundle directory.

Ideally, we'd be building in a subdirectory like build, but neobundle gave issues with that.  If anything interrupts the process, cleaning out the old build files can cause issues.

**Comment by tony** [comment]
@jeaye Are you using Neobundle / any tool to automate installing vim plugins?

**Comment by jeaye** [comment]
@tony My color_coded config: https://github.com/jeaye/vimrc/blob/master/config/color.vim

**Comment by jeaye** [comment]
What actual issues are you having with it? Aside from NeoBundle's poor UX, installing/updating color_coded hasn't been an issue on OS X (El Capitan) and Linux (various).

**Comment by tony** [comment]
This may be due to a failed compilation gunking up the bundle directory in various ways. I'm closing this until I find more information on it.

Thanks for showing your vimrc by the way.  Here's what I had:

```viml
NeoBundleLazy 'jeaye/color_coded', { 
      \ 'build': {
      \   'unix': 'cmake . && make && make install',
      \   'linux': 'cmake . -DCUSTOM_CLANG=1 -DLLVM_ROOT_PATH=/usr -DLLVM_INCLUDE_PATH=/usr/lib/llvm-3.4/include'
      \ },
      \ 'autoload' : { 'filetypes' : ['c', 'cpp', 'objc', 'objcpp'] },
      \ 'build_commands' : ['cmake', 'make'],
      \ 'external_commands' : ['clang']
      \}
```

src: https://github.com/tony/vim-config/blob/08ee4c0fde2757ffbeaa90c78d9c37ee7184f69b/bundles.d/lang.c-cxx.vim#L28
