### ISSUE TITLE
Lots of ID not found

### ISSUE THREAD

**Issue by oblitum** [jeaye/color_coded#9]
Open a C++ file in a split, close its window (don't delete the buffer), split again to original arrangement and switch to the same C++ file. You get a bunch of warnings about lost IDs.

**Comment by oblitum** [comment]
Also not sure whether you're experiencing this but when I switch from a first c++ file to another, the second gets a completely noisy highlighting.

**Comment by oblitum** [comment]
Not sure whether it's a problem with Vim refreshing though.

**Comment by oblitum** [comment]
Ah, this noisy highlithting in other buffers, iirc, is a regression. I think I've already discussed something about this on IRC...

**Comment by jeaye** [comment]
Yeah, I've been working on this issue this morning. It coincides with some splitting issues which already existed in color_coded; now they're just more visible. I have found a solution though, so it looks like I'll be able to push something up soon. Thanks!

**Comment by jeaye** [comment]
I've pushed up a commit to the `splits` branch which seems to've solved all of these issues. If you have the time, please play around with it. I'm testing splits, tabs, and everything in between. So far, it seems to be handling well.

**Comment by oblitum** [comment]
it seems to have fixed the "ID not found" errors, although there's still messy highlighting when loading other buffers.

**Comment by oblitum** [comment]
I mean, at last when loading other non-c++ buffers.

**Comment by jeaye** [comment]
Right you are. That was a regression from before, since I wasn't sure if it was still needed. Looks like it is!

**Comment by jeaye** [comment]
Let me know if you see any other issues. Hopefully things should be stabalizing and working nicely with your other plugins. :)

**Comment by oblitum** [comment]
All fine :)

**Comment by jeaye** [comment]
Alright! I'm hoping you're able to use this every day; my next big fix is folding, for which there's already an issue. Aside from that, and some misc cleanup and optimizations, everything else is relying on clang/llvm bugs (which are not likely to be merged anytime soon).

**Comment by oblitum** [comment]
@jeaye yeap, I'm planning to use it since I find it much better. The sole missing thing I dislike about it is trying to handle colorscheme instability. As you already know it's quite broken while typing, if there was a way to restrict this, it would be perfect. I was think of alternatives myself, like, trying to refresh highlighting in key situations, like going to normal mode solely, or when moving cursor line, or refreshing just when there're no errors in the TU, I don't know in truth =)

**Comment by jeaye** [comment]
On Sat, Mar 28, 2015 at 10:35:46PM -0700, Francisco Lopes wrote:
>    [1]@jeaye yeap, I'm planning to use it since I find it much better. The
>    sole missing thing I dislike about it is trying to handle colorscheme
>    instability. As you already know it's quite broken while typing, if there
>    was a way to restrict this, it would be perfect. I was think of
>    alternatives myself, like, trying to refresh highlighting in key
>    situations, like going to normal mode solely, or when moving cursor line,
>    or refreshing just when there're no errors in the TU, I don't know in
>    truth =)

Seems reasonable. How about an option for realtime (incomplete) updating which defaults to on? It seems like it'd be simple enough to guard the functionality between two cases:

1) Incomplete highlighting is enabled
2) There was a successful compilation

**Comment by oblitum** [comment]
> Seems reasonable. How about an option for realtime (incomplete) updating which defaults to on? It seems like it'd be simple enough to guard the functionality between two cases:

> 1) Incomplete highlighting is enabled
> 2) There was a successful compilation

Sounds good for me. If this option gets less instable and as usable, I guess it may turn to be the default? Let me know if you implement it, I'd like to try.

**Comment by jeaye** [comment]
Related to this issue, I've done a lot of work on improving buffer split support on the `revamp` branch. I'll be testing it out for a while before merging it with master and I encourage anyone interested to give it a go.

**Comment by oblitum** [comment]
@jeaye did the revamp branch get merged? I've checked your previous message only now, I'm still interested in highlighting with splits, does the revamp branch do this?

**Comment by jeaye** [comment]
Yeah, the revamp branch went in that week; it's been in for some time. If you're still having issues with splits, then there are still some issues with the vim handling.

**Comment by oblitum** [comment]
I've no issues, except that it only highlights one window, I'd like to get highlight in all..

**Comment by oblitum** [comment]
This didn't change right? It's still expected behaviour.

**Comment by oblitum** [comment]
Ah, nevermend, your comment is of same epoch as another issue about this.

**Comment by jeaye** [comment]
Handling highlighting in multiple windows, which could be the same buffer, results in vim giving color_coded one hell of a time. As it stands, I've intentionally made it so only one is highlighted at a time and vim is ok with that.

**Comment by oblitum** [comment]
I guess you added this comment here just to update anyone at that time with discussed that another issue.
