### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by hawk78** [jeaye/color_coded#91]
CONTEXT:

[lunedì 16 novembre 2015] [10:29:43 CET] <jeaye> vincenzo: Which OS?
[lunedì 16 novembre 2015] [10:30:08 CET] <jeaye> To check for luajit, try: vim --version | grep jit
[lunedì 16 novembre 2015] [10:30:23 CET] <vincenzo> I have no luajit, Im on ubuntu wily 64
[lunedì 16 novembre 2015] [10:31:13 CET] <vincenzo> I tried to compile against both the integrated and system llvm
[lunedì 16 novembre 2015] [10:31:22 CET] <vincenzo> both segfault

I have YCM syntastic and cc installed using phatogen. The problem happens some seconds after vim startup when editing .cpp files. 

EFFECT:
Vim: Caught deadly signal SEGV

**Comment by jeaye** [comment]
@hawk78 You mentioned in IRC that you're no longer seeing this. Can we close this issue?

**Comment by hawk78** [comment]
Hi I was not in my office during the last week. Sorry for not beeing
responsive. Ok also for "if it happens again I will reopen it with more
details".

Ciao
Vincenzo

**Comment by hawk78** [comment]
I got it again, this time I was able to capture a stack-trace.



Program terminated with signal SIGABRT, Aborted.
#0  0x00007f7c85777597 in kill () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: File o directory non esistente.
[Current thread is 1 (Thread 0x7f7c88013800 (LWP 27766))]
(gdb) bt
#0  0x00007f7c85777597 in kill () at ../sysdeps/unix/syscall-template.S:81
#1  0x00005619ef523873 in mch_exit ()
#2  <signal handler called>
#3  0x00007f7c85777267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#4  0x00007f7c85778eca in __GI_abort () at abort.c:89
#5  0x00007f7c82552b7d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f7c825509c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f7c82550a11 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f7c82d3c3de in color_coded::async::queue<color_coded::async::task, color_coded::async::result>::~queue() ()
   from /home/hawk/.vim/bundle/color_coded/bin/color_coded.so
#9  0x00007f7c8577bd32 in __run_exit_handlers (status=0, listp=0x7f7c85b06698 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#10 0x00007f7c8577bd85 in __GI_exit (status=<optimized out>) at exit.c:104
#11 0x00005619ef523867 in mch_exit ()
#12 0x00005619ef48bf02 in ?? ()
#13 0x00005619ef4921a7 in do_cmdline ()
#14 0x00005619ef4fe675 in ?? ()
#15 0x00005619ef50749b in normal_cmd ()
#16 0x00005619ef5cc325 in main_loop ()
#17 0x00005619ef4322e2 in main ()
