### ISSUE TITLE
bash-isms in build

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#95]
lib/track_api
lib/jest/configure
lib/jest/do_install (https://github.com/jeaye/jest)

all have bash hard-coded.

The only thing I was required to change to get it working was ``lib/track_api``. PR forthcoming.

FreeBSD / OpenBSD don't have bash on default install. I can go pretty far without having to worry about bash.

**Comment by jeaye** [comment]
On Sat, Nov 28, 2015 at 05:41:16PM -0800, Tony Narlock wrote:
>    lib/track_api
>    lib/jest/configure
>    lib/jest/do_install ([1]https://github.com/jeaye/jest)
> 
>    all have bash hard-coded.
> 
>    The only thing I was required to change to get it working was
>    lib/track_api. PR forthcoming.
> 
>    FreeBSD / OpenBSD don't have bash on default install. I can go pretty far
>    without having to worry about bash.

Yep, you're absolutely right. Writing bash shebangs is a bad habit for
me. I'm looking forward to that PR!
