### ISSUE TITLE
Vim versions supported

### ISSUE THREAD

**Issue by picanumber** [jeaye/color_coded#98]
My vim has the following version signature : 
"VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:34)"
Yet, when installing color_coded with Vundle I get the following error : 
>Done!
>color_coded unavailable: requires Vim 7.4p330+

Will support be added for for at least 7.4 ? If not, I've located the line that emmits this errors in the color_coded scripts; is there any chance things are going to be OK if I comment this line ?

**Comment by jeaye** [comment]
On Tue, Dec 08, 2015 at 03:32:38PM -0800, Nikos Athanasiou wrote:
>    My vim has the following version signature :
>    "VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 2 2014 19:39:34)"
>    Yet, when installing color_coded with Vundle I get the following error :
> 
>      Done!
>      color_coded unavailable: requires Vim 7.4p330+
> 
>    Will support be added for for at least 7.4 ? If not, I've located the line
>    that emmits this errors in the color_coded scripts; is there any chance
>    things are going to be OK if I comment this line ?

You can try! However, I don't think it'll work. You need `matchaddpos`,
which was added only in p330, I believe. Are you able to update vim?

**Comment by picanumber** [comment]
Ok, I ended up downloading the latest sources and building Vim. I was trying to avoid this because of all the stuff I had to reconfigure, but in retrospective it less trouble. All good now, thnx for this amazing plugin

**Comment by jeaye** [comment]
Glad to hear everything's working. Enjoy!
